In [1]:
import pandas as pd

In [2]:
data = {
    "Order_id": [1, 2, 3, 4, 5,6],
    "Region": ['North', 'South', 'East', 'West', 'North', 'South'],
    "Category": ["Electronics", "Clothing", "Home", "Electronics", "Clothing", "Home"],
    "Product": ["Laptop", "Shirt", "Sofa", "Smartphone", "Jeans", "Table"],
    "Sales": [1000, 1500, 1200, 2000, 1800, 1300],
    "Quantity": [10, 15, 12, 20, 18, 13]
}

In [3]:
df = pd.DataFrame(data)

In [4]:
df

   Order_id Region     Category     Product  Sales  Quantity
0         1  North  Electronics      Laptop   1000        10
1         2  South     Clothing       Shirt   1500        15
2         3   East         Home        Sofa   1200        12
3         4   West  Electronics  Smartphone   2000        20
4         5  North     Clothing       Jeans   1800        18
5         6  South         Home       Table   1300        13

In [5]:
df["Sales"].sum()

np.int64(8800)

In [6]:
df["Sales"].mean()

np.float64(1466.6666666666667)

In [7]:
df["Sales"].max()

np.int64(2000)

In [8]:
df["Sales"].min()

np.int64(1000)

In [10]:
df["Sales"].count()

np.int64(6)

In [11]:
df

   Order_id Region     Category     Product  Sales  Quantity
0         1  North  Electronics      Laptop   1000        10
1         2  South     Clothing       Shirt   1500        15
2         3   East         Home        Sofa   1200        12
3         4   West  Electronics  Smartphone   2000        20
4         5  North     Clothing       Jeans   1800        18
5         6  South         Home       Table   1300        13

In [12]:
df.groupby("Category")["Sales"].sum()

Category
Clothing       3300
Electronics    3000
Home           2500
Name: Sales, dtype: int64

In [13]:
df.groupby("Category")["Sales"].mean()

Category
Clothing       1650.0
Electronics    1500.0
Home           1250.0
Name: Sales, dtype: float64

In [14]:
df.groupby("Region")["Quantity"].sum()

Region
East     12
North    28
South    28
West     20
Name: Quantity, dtype: int64

In [16]:
df.groupby("Category")["Sales"].agg(["sum","mean","min","max","count"])
# select category, sum(sales), avg(sales)... from df

              sum    mean   min   max  count
Category
Clothing     3300  1650.0  1500  1800      2
Electronics  3000  1500.0  1000  2000      2
Home         2500  1250.0  1200  1300      2

In [17]:
df

   Order_id Region     Category     Product  Sales  Quantity
0         1  North  Electronics      Laptop   1000        10
1         2  South     Clothing       Shirt   1500        15
2         3   East         Home        Sofa   1200        12
3         4   West  Electronics  Smartphone   2000        20
4         5  North     Clothing       Jeans   1800        18
5         6  South         Home       Table   1300        13

In [18]:
df.groupby("Category").agg({"Sales":"sum", "Quantity":"sum"})

             Sales  Quantity
Category
Clothing      3300        33
Electronics   3000        30
Home          2500        25

In [19]:
df.groupby("Region")["Order_id"].count()

Region
East     1
North    2
South    2
West     1
Name: Order_id, dtype: int64

In [23]:
import numpy as np 
np.nan  # Not a Number  # Special FLoating point number  # NULL  # Undefined or Missing Data

nan

In [24]:
data_with_missing = {
    "EmpID": [1, 2, 3, 4, 5],
    "Name": ['John', 'Jane', 'Doe', 'Alice', 'Bob'],
    "Department": ['HR', 'Finance', np.nan, 'IT', 'Marketing'],
    "Salary": [50000, 60000, 55000, np.nan, 65000],
    "Experience": [5, 7, np.nan, 4, 6]
}

In [26]:
df = pd.DataFrame(data_with_missing)

In [27]:
df

   EmpID   Name Department   Salary  Experience
0      1   John         HR  50000.0         5.0
1      2   Jane    Finance  60000.0         7.0
2      3    Doe        NaN  55000.0         NaN
3      4  Alice         IT      NaN         4.0
4      5    Bob  Marketing  65000.0         6.0

In [28]:
df.isna()

   EmpID   Name  Department  Salary  Experience
0  False  False       False   False       False
1  False  False       False   False       False
2  False  False        True   False        True
3  False  False       False    True       False
4  False  False       False   False       False

In [29]:
df.isna().sum()

EmpID         0
Name          0
Department    1
Salary        1
Experience    1
dtype: int64

In [30]:
df.isna().any()

EmpID         False
Name          False
Department     True
Salary         True
Experience     True
dtype: bool

In [31]:
df.isna().sum().sum()

np.int64(3)

In [33]:
df

   EmpID   Name Department   Salary  Experience
0      1   John         HR  50000.0         5.0
1      2   Jane    Finance  60000.0         7.0
2      3    Doe        NaN  55000.0         NaN
3      4  Alice         IT      NaN         4.0
4      5    Bob  Marketing  65000.0         6.0

In [35]:
df[df.isna().any(axis=1)]   #  Extract records with atleast one null value

   EmpID   Name Department   Salary  Experience
2      3    Doe        NaN  55000.0         NaN
3      4  Alice         IT      NaN         4.0

In [36]:
df[df["Salary"].isna()]

   EmpID   Name Department  Salary  Experience
3      4  Alice         IT     NaN         4.0

In [37]:
df

   EmpID   Name Department   Salary  Experience
0      1   John         HR  50000.0         5.0
1      2   Jane    Finance  60000.0         7.0
2      3    Doe        NaN  55000.0         NaN
3      4  Alice         IT      NaN         4.0
4      5    Bob  Marketing  65000.0         6.0

In [38]:
df.dropna()

   EmpID  Name Department   Salary  Experience
0      1  John         HR  50000.0         5.0
1      2  Jane    Finance  60000.0         7.0
4      5   Bob  Marketing  65000.0         6.0

In [39]:
df

   EmpID   Name Department   Salary  Experience
0      1   John         HR  50000.0         5.0
1      2   Jane    Finance  60000.0         7.0
2      3    Doe        NaN  55000.0         NaN
3      4  Alice         IT      NaN         4.0
4      5    Bob  Marketing  65000.0         6.0

In [40]:
df.dropna(inplace=True)

In [41]:
df

   EmpID  Name Department   Salary  Experience
0      1  John         HR  50000.0         5.0
1      2  Jane    Finance  60000.0         7.0
4      5   Bob  Marketing  65000.0         6.0

In [42]:
df = pd.DataFrame(data_with_missing)

In [43]:
df

   EmpID   Name Department   Salary  Experience
0      1   John         HR  50000.0         5.0
1      2   Jane    Finance  60000.0         7.0
2      3    Doe        NaN  55000.0         NaN
3      4  Alice         IT      NaN         4.0
4      5    Bob  Marketing  65000.0         6.0

In [44]:
df["Salary"].mean()

np.float64(57500.0)

In [45]:
df.fillna("No Value")

   EmpID   Name Department    Salary Experience
0      1   John         HR   50000.0        5.0
1      2   Jane    Finance   60000.0        7.0
2      3    Doe   No Value   55000.0   No Value
3      4  Alice         IT  No Value        4.0
4      5    Bob  Marketing   65000.0        6.0

In [46]:
df['Salary'].fillna(df["Salary"].mean())

0    50000.0
1    60000.0
2    55000.0
3    57500.0
4    65000.0
Name: Salary, dtype: float64

In [47]:
df

   EmpID   Name Department   Salary  Experience
0      1   John         HR  50000.0         5.0
1      2   Jane    Finance  60000.0         7.0
2      3    Doe        NaN  55000.0         NaN
3      4  Alice         IT      NaN         4.0
4      5    Bob  Marketing  65000.0         6.0

In [50]:
df['Salary'].fillna(df["Salary"].mean(),inplace=True)

C:\Users\Chinna\AppData\Local\Temp\ipykernel_12580\1073604309.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df["Salary"].mean(),inplace=True)

In [51]:
df.fillna({"Salary":df["Salary"].mean()},inplace=True)

In [52]:
df

   EmpID   Name Department   Salary  Experience
0      1   John         HR  50000.0         5.0
1      2   Jane    Finance  60000.0         7.0
2      3    Doe        NaN  55000.0         NaN
3      4  Alice         IT  57500.0         4.0
4      5    Bob  Marketing  65000.0         6.0

In [53]:
df.fillna({"Department":"Unknown"}, inplace=True)

In [54]:
df

   EmpID   Name Department   Salary  Experience
0      1   John         HR  50000.0         5.0
1      2   Jane    Finance  60000.0         7.0
2      3    Doe    Unknown  55000.0         NaN
3      4  Alice         IT  57500.0         4.0
4      5    Bob  Marketing  65000.0         6.0

In [55]:
df

   EmpID   Name Department   Salary  Experience
0      1   John         HR  50000.0         5.0
1      2   Jane    Finance  60000.0         7.0
2      3    Doe    Unknown  55000.0         NaN
3      4  Alice         IT  57500.0         4.0
4      5    Bob  Marketing  65000.0         6.0

In [56]:
df["Experience"].fillna(method="bfill")

C:\Users\Chinna\AppData\Local\Temp\ipykernel_12580\2796348022.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Experience"].fillna(method="bfill")

0    5.0
1    7.0
2    4.0
3    4.0
4    6.0
Name: Experience, dtype: float64

In [57]:
df["Experience"].fillna(method="ffill")

C:\Users\Chinna\AppData\Local\Temp\ipykernel_12580\2527435558.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Experience"].fillna(method="ffill")

0    5.0
1    7.0
2    7.0
3    4.0
4    6.0
Name: Experience, dtype: float64

In [58]:
df

   EmpID   Name Department   Salary  Experience
0      1   John         HR  50000.0         5.0
1      2   Jane    Finance  60000.0         7.0
2      3    Doe    Unknown  55000.0         NaN
3      4  Alice         IT  57500.0         4.0
4      5    Bob  Marketing  65000.0         6.0

In [59]:
df["Experience"].replace(np.nan,0)

0    5.0
1    7.0
2    0.0
3    4.0
4    6.0
Name: Experience, dtype: float64

In [60]:
df

   EmpID   Name Department   Salary  Experience
0      1   John         HR  50000.0         5.0
1      2   Jane    Finance  60000.0         7.0
2      3    Doe    Unknown  55000.0         NaN
3      4  Alice         IT  57500.0         4.0
4      5    Bob  Marketing  65000.0         6.0

In [61]:
df["Experience"] = df["Experience"].replace(np.nan,0)

In [62]:
df

   EmpID   Name Department   Salary  Experience
0      1   John         HR  50000.0         5.0
1      2   Jane    Finance  60000.0         7.0
2      3    Doe    Unknown  55000.0         0.0
3      4  Alice         IT  57500.0         4.0
4      5    Bob  Marketing  65000.0         6.0

In [63]:
# merge

In [70]:
employees_df = pd.DataFrame({
    "emp_id": [1, 2, 3, 4, 5],
    "name": ['John', 'Jane', 'Doe', 'Alice', 'Bob'],
    "dept_id": [101, 102, 103, 102, 105],
    "salary": [50000, 60000, 55000, 70000, 65000]
})

In [71]:
departments_df = pd.DataFrame({
    "dept_id": [101, 102, 103, 104],
    "department": ['HR', 'Finance', 'IT', 'Marketing']    
})

In [72]:
employees_df

   emp_id   name  dept_id  salary
0       1   John      101   50000
1       2   Jane      102   60000
2       3    Doe      103   55000
3       4  Alice      102   70000
4       5    Bob      105   65000

In [73]:
departments_df

   dept_id department
0      101         HR
1      102    Finance
2      103         IT
3      104  Marketing

In [74]:
pd.merge(employees_df,departments_df, on="dept_id", how="inner")

   emp_id   name  dept_id  salary department
0       1   John      101   50000         HR
1       2   Jane      102   60000    Finance
2       3    Doe      103   55000         IT
3       4  Alice      102   70000    Finance

In [75]:
pd.merge(employees_df,departments_df, on="dept_id", how="left")

   emp_id   name  dept_id  salary department
0       1   John      101   50000         HR
1       2   Jane      102   60000    Finance
2       3    Doe      103   55000         IT
3       4  Alice      102   70000    Finance
4       5    Bob      105   65000        NaN

In [76]:
pd.merge(employees_df,departments_df, on="dept_id", how="right")

   emp_id   name  dept_id   salary department
0     1.0   John      101  50000.0         HR
1     2.0   Jane      102  60000.0    Finance
2     4.0  Alice      102  70000.0    Finance
3     3.0    Doe      103  55000.0         IT
4     NaN    NaN      104      NaN  Marketing

In [77]:
pd.merge(employees_df,departments_df, on="dept_id", how="outer")

   emp_id   name  dept_id   salary department
0     1.0   John      101  50000.0         HR
1     2.0   Jane      102  60000.0    Finance
2     4.0  Alice      102  70000.0    Finance
3     3.0    Doe      103  55000.0         IT
4     NaN    NaN      104      NaN  Marketing
5     5.0    Bob      105  65000.0        NaN

In [79]:
employees_df = pd.DataFrame({
    "emp_id": [1, 2, 3, 4, 5],
    "name": ['John', 'Jane', 'Doe', 'Alice', 'Bob'],
    "dept_id": [101, 102, 103, 102, 105],
    "salary": [50000, 60000, 55000, 70000, 65000]
})

In [80]:
departments_df = pd.DataFrame({
    "id": [101, 102, 103, 104],
    "department": ['HR', 'Finance', 'IT', 'Marketing']    
})

In [84]:
pd.merge(employees_df,departments_df, left_on="dept_id", right_on="id",  how="inner")

   emp_id   name  dept_id  salary   id department
0       1   John      101   50000  101         HR
1       2   Jane      102   60000  102    Finance
2       3    Doe      103   55000  103         IT
3       4  Alice      102   70000  102    Finance

In [85]:
# join   #  index-based

In [86]:
order_df = pd.DataFrame({"order_id": [1, 2, 3, 4, 5],
                         "customer_id": [101, 102, 103, 104, 105],
                         "order_amount": [1000, 1500, 1200, 2000, 1800]})

In [87]:
customer_df = pd.DataFrame({"customer_id": [101, 102, 103, 104, 105],
                            "customer_name": ['Alice', 'Bob', 'Charlie', 'David', 'Eve']})

In [88]:
order_df

   order_id  customer_id  order_amount
0         1          101          1000
1         2          102          1500
2         3          103          1200
3         4          104          2000
4         5          105          1800

In [89]:
customer_df

   customer_id customer_name
0          101         Alice
1          102           Bob
2          103       Charlie
3          104         David
4          105           Eve

In [90]:
pd.merge(order_df,customer_df,on="customer_id", how="inner")

   order_id  customer_id  order_amount customer_name
0         1          101          1000         Alice
1         2          102          1500           Bob
2         3          103          1200       Charlie
3         4          104          2000         David
4         5          105          1800           Eve

In [91]:
order_df.join(customer_df.set_index("customer_id"), on="customer_id")

   order_id  customer_id  order_amount customer_name
0         1          101          1000         Alice
1         2          102          1500           Bob
2         3          103          1200       Charlie
3         4          104          2000         David
4         5          105          1800           Eve

In [92]:
sales_df = pd.DataFrame({
    "product_name": ["Laptop", "Shirt", "Sofa", "Smartphone", "Jeans"],
    "Region": ['North', 'South', 'East', 'West', 'North'],
    "Year": [2020, 2020, 2021, 2021, 2022],
    "Sales": [1000, 1500, 1200, 2000, 1800]
})

In [93]:
targer_sales_df = pd.DataFrame({
    "product_name": ["Laptop", "Shirt", "Sofa", "Smartphone", "Jeans"],
    "Region": ['North', 'South', 'East', 'West', 'North'],
    "Year": [2020, 2020, 2021, 2021, 2022],
    "Target_Sales": [1100, 1400, 1300, 1900, 1700]
})

In [95]:
pd.merge(sales_df,targer_sales_df, on= ["product_name","Region", "Year"], how="inner")

  product_name Region  Year  Sales  Target_Sales
0       Laptop  North  2020   1000          1100
1        Shirt  South  2020   1500          1400
2         Sofa   East  2021   1200          1300
3   Smartphone   West  2021   2000          1900
4        Jeans  North  2022   1800          1700