In [1]:
import pandas as pd

In [2]:
raw_data = pd.DataFrame({
    "Emp Id": [1, 2, 3, 4, 5],
    "Emp-Names": ['John', 'Jane', 'Doe', 'Alice', 'Bob'],
    "DEPT": ['HR', 'Finance', 'IT', 'Marketing', 'Sales'],
    "Salary(INR)": [50000, 60000, 55000, 70000, 65000],
    "Joining Date": ['2020-01-15', '2019-03-20', '2021-07-10', '2018-11-05', '2020-06-25']
})

In [3]:
raw_data

   Emp Id Emp-Names       DEPT  Salary(INR) Joining Date
0       1      John         HR        50000   2020-01-15
1       2      Jane    Finance        60000   2019-03-20
2       3       Doe         IT        55000   2021-07-10
3       4     Alice  Marketing        70000   2018-11-05
4       5       Bob      Sales        65000   2020-06-25

In [4]:
df = raw_data.copy()

In [5]:
df

   Emp Id Emp-Names       DEPT  Salary(INR) Joining Date
0       1      John         HR        50000   2020-01-15
1       2      Jane    Finance        60000   2019-03-20
2       3       Doe         IT        55000   2021-07-10
3       4     Alice  Marketing        70000   2018-11-05
4       5       Bob      Sales        65000   2020-06-25

In [7]:
df.columns

Index(['Emp Id', 'Emp-Names', 'DEPT', 'Salary(INR)', 'Joining Date'], dtype='object')

In [9]:
(df.columns.str.strip().str.lower().str.replace(" ","_"))

Index(['emp_id', 'emp-names', 'dept', 'salary(inr)', 'joining_date'], dtype='object')

In [11]:
(df.columns.str.strip().str.lower().str.replace(" ","_").str.replace("-","_").str.replace("[()]","",regex=True))

Index(['emp_id', 'emp_names', 'dept', 'salaryinr', 'joining_date'], dtype='object')

In [12]:
df.columns = (df.columns.str.strip().str.lower().str.replace(" ","_").str.replace("-","_").str.replace("[()]","",regex=True))

In [13]:
df

   emp_id emp_names       dept  salaryinr joining_date
0       1      John         HR      50000   2020-01-15
1       2      Jane    Finance      60000   2019-03-20
2       3       Doe         IT      55000   2021-07-10
3       4     Alice  Marketing      70000   2018-11-05
4       5       Bob      Sales      65000   2020-06-25

In [14]:
df.rename(columns={"salaryinr":"salary"})

   emp_id emp_names       dept  salary joining_date
0       1      John         HR   50000   2020-01-15
1       2      Jane    Finance   60000   2019-03-20
2       3       Doe         IT   55000   2021-07-10
3       4     Alice  Marketing   70000   2018-11-05
4       5       Bob      Sales   65000   2020-06-25

In [15]:
df

   emp_id emp_names       dept  salaryinr joining_date
0       1      John         HR      50000   2020-01-15
1       2      Jane    Finance      60000   2019-03-20
2       3       Doe         IT      55000   2021-07-10
3       4     Alice  Marketing      70000   2018-11-05
4       5       Bob      Sales      65000   2020-06-25

In [16]:
df.rename(columns={"salaryinr":"salary"},inplace=True)

In [17]:
df

   emp_id emp_names       dept  salary joining_date
0       1      John         HR   50000   2020-01-15
1       2      Jane    Finance   60000   2019-03-20
2       3       Doe         IT   55000   2021-07-10
3       4     Alice  Marketing   70000   2018-11-05
4       5       Bob      Sales   65000   2020-06-25

In [18]:
df.dtypes

emp_id           int64
emp_names       object
dept            object
salary           int64
joining_date    object
dtype: object

In [19]:
df["joining_date"] = pd.to_datetime(df["joining_date"])

In [20]:
df.dtypes

emp_id                   int64
emp_names               object
dept                    object
salary                   int64
joining_date    datetime64[ns]
dtype: object

In [21]:
df["emp_id"] = df["emp_id"].astype(int)

In [22]:
df.dtypes

emp_id                   int64
emp_names               object
dept                    object
salary                   int64
joining_date    datetime64[ns]
dtype: object

In [23]:
df

   emp_id emp_names       dept  salary joining_date
0       1      John         HR   50000   2020-01-15
1       2      Jane    Finance   60000   2019-03-20
2       3       Doe         IT   55000   2021-07-10
3       4     Alice  Marketing   70000   2018-11-05
4       5       Bob      Sales   65000   2020-06-25

In [24]:
df["dept"] = df["dept"].str.upper()

In [25]:
df

   emp_id emp_names       dept  salary joining_date
0       1      John         HR   50000   2020-01-15
1       2      Jane    FINANCE   60000   2019-03-20
2       3       Doe         IT   55000   2021-07-10
3       4     Alice  MARKETING   70000   2018-11-05
4       5       Bob      SALES   65000   2020-06-25

In [26]:
# Sales Data Cleaning Pipeline

In [44]:
sales_raw = pd.DataFrame({
    "Order ID": [1, 2, 3, 4, 5],
    "Customer Id": [101, 102, 103, 104, 105],
    "Product Id": ["P1", "P2", "P3", "P3", "P2"],
    "Region": ['North', 'South', 'East', 'West', 'North'],  
    "Sales Amount": [1000, 1500, 1200, None, 1800],
    "Order Date": ['2020-01-15', '2020-02-20', '2021-03-10', '2021-04-05', '2022-05-25']
})

In [45]:
sales_raw

   Order ID  Customer Id Product Id Region  Sales Amount  Order Date
0         1          101         P1  North        1000.0  2020-01-15
1         2          102         P2  South        1500.0  2020-02-20
2         3          103         P3   East        1200.0  2021-03-10
3         4          104         P3   West           NaN  2021-04-05
4         5          105         P2  North        1800.0  2022-05-25

In [46]:
product_raw = pd.DataFrame({
    "Product Id": ["P1", "P2", "P3"],
    "Product Name": ["Laptop", "Shirt", "Sofa"],
    "category": ["Electronics", "Clothing", "Home"]
})

In [47]:
product_raw

  Product Id Product Name     category
0         P1       Laptop  Electronics
1         P2        Shirt     Clothing
2         P3         Sofa         Home

In [48]:
sales_raw.columns

Index(['Order ID', 'Customer Id', 'Product Id', 'Region', 'Sales Amount',
       'Order Date'],
      dtype='object')

In [49]:
sales_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      5 non-null      int64
 1   Customer Id   5 non-null      int64
 2   Product Id    5 non-null      object
 3   Region        5 non-null      object
 4   Sales Amount  4 non-null      float64
 5   Order Date    5 non-null      object
dtypes: float64(1), int64(2), object(3)
memory usage: 372.0+ bytes

In [50]:
sales = sales_raw.copy()

In [51]:
sales.columns = (sales.columns.str.replace(" ","_").str.lower())

In [52]:
sales

   order_id  customer_id product_id region  sales_amount  order_date
0         1          101         P1  North        1000.0  2020-01-15
1         2          102         P2  South        1500.0  2020-02-20
2         3          103         P3   East        1200.0  2021-03-10
3         4          104         P3   West           NaN  2021-04-05
4         5          105         P2  North        1800.0  2022-05-25

In [53]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      5 non-null      int64
 1   customer_id   5 non-null      int64
 2   product_id    5 non-null      object
 3   region        5 non-null      object
 4   sales_amount  4 non-null      float64
 5   order_date    5 non-null      object
dtypes: float64(1), int64(2), object(3)
memory usage: 372.0+ bytes

In [54]:
sales["order_date"] = pd.to_datetime(sales["order_date"])

In [55]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      5 non-null      int64
 1   customer_id   5 non-null      int64
 2   product_id    5 non-null      object
 3   region        5 non-null      object
 4   sales_amount  4 non-null      float64
 5   order_date    5 non-null      datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 372.0+ bytes

In [56]:
sales

   order_id  customer_id product_id region  sales_amount order_date
0         1          101         P1  North        1000.0 2020-01-15
1         2          102         P2  South        1500.0 2020-02-20
2         3          103         P3   East        1200.0 2021-03-10
3         4          104         P3   West           NaN 2021-04-05
4         5          105         P2  North        1800.0 2022-05-25

In [57]:
sales.isna()

   order_id  customer_id  product_id  region  sales_amount  order_date
0     False        False       False   False         False       False
1     False        False       False   False         False       False
2     False        False       False   False         False       False
3     False        False       False   False          True       False
4     False        False       False   False         False       False

In [58]:
sales.isna().sum()

order_id        0
customer_id     0
product_id      0
region          0
sales_amount    1
order_date      0
dtype: int64

In [59]:
sales["sales_amount"].mean()

np.float64(1375.0)

In [60]:
sales["sales_amount"].fillna(sales["sales_amount"].mean())

0    1000.0
1    1500.0
2    1200.0
3    1375.0
4    1800.0
Name: sales_amount, dtype: float64

In [61]:
sales

   order_id  customer_id product_id region  sales_amount order_date
0         1          101         P1  North        1000.0 2020-01-15
1         2          102         P2  South        1500.0 2020-02-20
2         3          103         P3   East        1200.0 2021-03-10
3         4          104         P3   West           NaN 2021-04-05
4         5          105         P2  North        1800.0 2022-05-25

In [62]:
sales["sales_amount"].fillna(sales["sales_amount"].mean(),inplace=True)

C:\Users\Chinna\AppData\Local\Temp\ipykernel_5976\1868453458.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sales["sales_amount"].fillna(sales["sales_amount"].mean(),inplace=True)

In [63]:
sales.fillna({"sales_amount":sales["sales_amount"].mean()},inplace=True)

In [64]:
sales

   order_id  customer_id product_id region  sales_amount order_date
0         1          101         P1  North        1000.0 2020-01-15
1         2          102         P2  South        1500.0 2020-02-20
2         3          103         P3   East        1200.0 2021-03-10
3         4          104         P3   West        1375.0 2021-04-05
4         5          105         P2  North        1800.0 2022-05-25

In [65]:
sales

   order_id  customer_id product_id region  sales_amount order_date
0         1          101         P1  North        1000.0 2020-01-15
1         2          102         P2  South        1500.0 2020-02-20
2         3          103         P3   East        1200.0 2021-03-10
3         4          104         P3   West        1375.0 2021-04-05
4         5          105         P2  North        1800.0 2022-05-25

In [68]:
df = sales[sales["sales_amount"]<=1500]

In [69]:
df

   order_id  customer_id product_id region  sales_amount order_date
0         1          101         P1  North        1000.0 2020-01-15
1         2          102         P2  South        1500.0 2020-02-20
2         3          103         P3   East        1200.0 2021-03-10
3         4          104         P3   West        1375.0 2021-04-05

In [72]:
df.sort_values(by="sales_amount", ascending= False,inplace=True)

C:\Users\Chinna\AppData\Local\Temp\ipykernel_5976\809801825.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.sort_values(by="sales_amount", ascending= False,inplace=True)

In [73]:
df

   order_id  customer_id product_id region  sales_amount order_date
1         2          102         P2  South        1500.0 2020-02-20
3         4          104         P3   West        1375.0 2021-04-05
2         3          103         P3   East        1200.0 2021-03-10
0         1          101         P1  North        1000.0 2020-01-15

In [74]:
product_raw

  Product Id Product Name     category
0         P1       Laptop  Electronics
1         P2        Shirt     Clothing
2         P3         Sofa         Home

In [75]:
product_raw.columns = (product_raw.columns.str.replace(" ","_").str.lower())

In [76]:
product_raw

  product_id product_name     category
0         P1       Laptop  Electronics
1         P2        Shirt     Clothing
2         P3         Sofa         Home

In [78]:
sales_with_cat_df = pd.merge(df,product_raw, on = "product_id", how="inner")

In [79]:
sales_with_cat_df

,order_id,customer_id,product_id,region,sales_amount,order_date,product_name,category
0,2,102,P2,South,1500.0,2020-02-20,Shirt,Clothing
1,4,104,P3,West,1375.0,2021-04-05,Sofa,Home
2,3,103,P3,East,1200.0,2021-03-10,Sofa,Home
3,1,101,P1,North,1000.0,2020-01-15,Laptop,Electronics

In [80]:
sales_with_cat_df.groupby("category")["sales_amount"].sum()

category
Clothing       1500.0
Electronics    1000.0
Home           2575.0
Name: sales_amount, dtype: float64

In [81]:
sales_with_cat_df.groupby("region")["sales_amount"].sum()

region
East     1200.0
North    1000.0
South    1500.0
West     1375.0
Name: sales_amount, dtype: float64

In [82]:
sales_with_cat_df.to_csv("sales_with_cat_df.csv")

In [84]:
sales_with_cat_df.to_csv("sales_with_cat_df.csv", index=False)

In [86]:
sales_with_cat_df.to_excel("sales_with_cat_df.xlsx")

In [87]:
sales_with_cat_df.to_excel("sales_with_cat_df.xlsx",index=False)

In [88]:
cust_df = pd.read_json("cust.json")

In [89]:
cust_df

,id,name,email,phone,address,registeredDate
0,1,John Smith,john.smith@example.com,+1-555-0101,"123 Main St, New York, NY 10001",2023-01-15
1,2,Sarah Johnson,sarah.j@example.com,+1-555-0102,"456 Oak Ave, Los Angeles, CA 90001",2023-06-20
2,3,Michael Chen,m.chen@example.com,+1-555-0103,"789 Pine Rd, Chicago, IL 60601",2024-02-10

In [90]:
order_df = pd.read_csv("order.csv")

In [93]:
order_df.head(2)

   order_id  customer_name product  quantity   price  order_date     status
0      1001     John Smith  Laptop         1  999.99  2025-01-15  Completed
1      1002  Sarah Johnson   Mouse         5   29.99  2025-01-16  Completed

In [94]:
order_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       15 non-null     int64
 1   customer_name  15 non-null     object
 2   product        15 non-null     object
 3   quantity       15 non-null     int64
 4   price          15 non-null     float64
 5   order_date     15 non-null     object
 6   status         15 non-null     object
dtypes: float64(1), int64(2), object(4)
memory usage: 972.0+ bytes