In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("order.csv")

In [3]:
df

,order_id,customer_name,product,quantity,price,order_date,status
0,1001,John Smith,Laptop,1,999.99,2025-01-15,Completed
1,1002,Sarah Johnson,Mouse,5,29.99,2025-01-16,Completed
2,1003,Mike Davis,Keyboard,2,79.99,2025-01-17,Pending
3,1004,Emma Wilson,Monitor,1,349.99,2025-01-18,Shipped
4,1005,James Brown,Headphones,3,149.99,2025-01-19,Completed
5,1006,Lisa Anderson,USB Cable,10,9.99,2025-01-20,Pending
6,1007,Robert Taylor,Webcam,2,89.99,2025-01-21,Completed
7,1008,Jennifer White,SSD 1TB,4,119.99,2025-01-22,Shipped
8,1009,David Martinez,RAM 16GB,1,159.99,2025-01-23,Pending
9,1010,Michelle Lee,Power Bank,6,39.99,2025-01-24,Completed
10,1011,Chris Garcia,Speaker,2,199.99,2025-01-25,Shipped
11,1012,Amanda Rodriguez,Desk Lamp,1,49.99,2025-01-26,Completed
12,1013,Kevin Miller,Phone Stand,8,19.99,2025-01-27,Pending
13,1014,Jessica Davis,External HDD 2TB,3,79.99,2025-01-28,Completed
14,1015,Brandon Wilson,Monitor Stand,2,59.99,2025-01-29,Shipped

In [4]:
df.sort_values("product")

,order_id,customer_name,product,quantity,price,order_date,status
11,1012,Amanda Rodriguez,Desk Lamp,1,49.99,2025-01-26,Completed
13,1014,Jessica Davis,External HDD 2TB,3,79.99,2025-01-28,Completed
4,1005,James Brown,Headphones,3,149.99,2025-01-19,Completed
2,1003,Mike Davis,Keyboard,2,79.99,2025-01-17,Pending
0,1001,John Smith,Laptop,1,999.99,2025-01-15,Completed
3,1004,Emma Wilson,Monitor,1,349.99,2025-01-18,Shipped
14,1015,Brandon Wilson,Monitor Stand,2,59.99,2025-01-29,Shipped
1,1002,Sarah Johnson,Mouse,5,29.99,2025-01-16,Completed
12,1013,Kevin Miller,Phone Stand,8,19.99,2025-01-27,Pending
9,1010,Michelle Lee,Power Bank,6,39.99,2025-01-24,Completed
8,1009,David Martinez,RAM 16GB,1,159.99,2025-01-23,Pending
7,1008,Jennifer White,SSD 1TB,4,119.99,2025-01-22,Shipped
10,1011,Chris Garcia,Speaker,2,199.99,2025-01-25,Shipped
5,1006,Lisa Anderson,USB Cable,10,9.99,2025-01-20,Pending
6,1007,Robert Taylor,Webcam,2,89.99,2025-01-21,Completed

In [6]:
df.sort_values("price")

,order_id,customer_name,product,quantity,price,order_date,status
5,1006,Lisa Anderson,USB Cable,10,9.99,2025-01-20,Pending
12,1013,Kevin Miller,Phone Stand,8,19.99,2025-01-27,Pending
1,1002,Sarah Johnson,Mouse,5,29.99,2025-01-16,Completed
9,1010,Michelle Lee,Power Bank,6,39.99,2025-01-24,Completed
11,1012,Amanda Rodriguez,Desk Lamp,1,49.99,2025-01-26,Completed
14,1015,Brandon Wilson,Monitor Stand,2,59.99,2025-01-29,Shipped
2,1003,Mike Davis,Keyboard,2,79.99,2025-01-17,Pending
13,1014,Jessica Davis,External HDD 2TB,3,79.99,2025-01-28,Completed
6,1007,Robert Taylor,Webcam,2,89.99,2025-01-21,Completed
7,1008,Jennifer White,SSD 1TB,4,119.99,2025-01-22,Shipped
4,1005,James Brown,Headphones,3,149.99,2025-01-19,Completed
8,1009,David Martinez,RAM 16GB,1,159.99,2025-01-23,Pending
10,1011,Chris Garcia,Speaker,2,199.99,2025-01-25,Shipped
3,1004,Emma Wilson,Monitor,1,349.99,2025-01-18,Shipped
0,1001,John Smith,Laptop,1,999.99,2025-01-15,Completed

In [7]:
df.sort_values("price",ascending=False)

,order_id,customer_name,product,quantity,price,order_date,status
0,1001,John Smith,Laptop,1,999.99,2025-01-15,Completed
3,1004,Emma Wilson,Monitor,1,349.99,2025-01-18,Shipped
10,1011,Chris Garcia,Speaker,2,199.99,2025-01-25,Shipped
8,1009,David Martinez,RAM 16GB,1,159.99,2025-01-23,Pending
4,1005,James Brown,Headphones,3,149.99,2025-01-19,Completed
7,1008,Jennifer White,SSD 1TB,4,119.99,2025-01-22,Shipped
6,1007,Robert Taylor,Webcam,2,89.99,2025-01-21,Completed
2,1003,Mike Davis,Keyboard,2,79.99,2025-01-17,Pending
13,1014,Jessica Davis,External HDD 2TB,3,79.99,2025-01-28,Completed
14,1015,Brandon Wilson,Monitor Stand,2,59.99,2025-01-29,Shipped
11,1012,Amanda Rodriguez,Desk Lamp,1,49.99,2025-01-26,Completed
9,1010,Michelle Lee,Power Bank,6,39.99,2025-01-24,Completed
1,1002,Sarah Johnson,Mouse,5,29.99,2025-01-16,Completed
12,1013,Kevin Miller,Phone Stand,8,19.99,2025-01-27,Pending
5,1006,Lisa Anderson,USB Cable,10,9.99,2025-01-20,Pending

In [8]:
df = pd.DataFrame({"Name": ["Alice", "Bob", "Charlie","David","Eva"],
                   "Dept": ["HR", "IT", "Finance","HR","IT"],
                   "Salary": [70000, 80000, 90000, 80000, 85000],
                   "Age": [25, 26, 25, 28, 25]})

In [9]:
df

      Name     Dept  Salary  Age
0    Alice       HR   70000   25
1      Bob       IT   80000   26
2  Charlie  Finance   90000   25
3    David       HR   80000   28
4      Eva       IT   85000   25

In [11]:
df.sort_values("Dept",ascending=False)  # Single column sort

      Name     Dept  Salary  Age
1      Bob       IT   80000   26
4      Eva       IT   85000   25
0    Alice       HR   70000   25
3    David       HR   80000   28
2  Charlie  Finance   90000   25

In [12]:
df.sort_values(["Dept","Age"],ascending=[False,True]) # Multiple column sort

      Name     Dept  Salary  Age
4      Eva       IT   85000   25
1      Bob       IT   80000   26
0    Alice       HR   70000   25
3    David       HR   80000   28
2  Charlie  Finance   90000   25

In [13]:
df

      Name     Dept  Salary  Age
0    Alice       HR   70000   25
1      Bob       IT   80000   26
2  Charlie  Finance   90000   25
3    David       HR   80000   28
4      Eva       IT   85000   25

In [14]:
df.sort_values(["Dept","Age"],ascending=[False,True],inplace=True)

In [15]:
df

      Name     Dept  Salary  Age
4      Eva       IT   85000   25
1      Bob       IT   80000   26
0    Alice       HR   70000   25
3    David       HR   80000   28
2  Charlie  Finance   90000   25

In [16]:
df.sort_index()

      Name     Dept  Salary  Age
0    Alice       HR   70000   25
1      Bob       IT   80000   26
2  Charlie  Finance   90000   25
3    David       HR   80000   28
4      Eva       IT   85000   25

In [17]:
df

      Name     Dept  Salary  Age
4      Eva       IT   85000   25
1      Bob       IT   80000   26
0    Alice       HR   70000   25
3    David       HR   80000   28
2  Charlie  Finance   90000   25

In [18]:
df.sort_index(inplace=True)

In [19]:
df

      Name     Dept  Salary  Age
0    Alice       HR   70000   25
1      Bob       IT   80000   26
2  Charlie  Finance   90000   25
3    David       HR   80000   28
4      Eva       IT   85000   25

In [22]:
df = pd.DataFrame({"Name":["Abe","Bob","Charam"],"Age":[20,30,40],"City":["Hyd","Chennai","Blr"]})

In [23]:
df

     Name  Age     City
0     Abe   20      Hyd
1     Bob   30  Chennai
2  Charam   40      Blr

In [24]:
df.loc[1]

Name        Bob
Age          30
City    Chennai
Name: 1, dtype: object

In [25]:
df = pd.DataFrame({"Name":["Abe","Bob","Charam"],"Age":[20,30,40],"City":["Hyd","Chennai","Blr"]}, index=["rec_1","rec_2","rec_3"])

In [26]:
df

         Name  Age     City
rec_1     Abe   20      Hyd
rec_2     Bob   30  Chennai
rec_3  Charam   40      Blr

In [29]:
df.loc['rec_2']

Name        Bob
Age          30
City    Chennai
Name: rec_2, dtype: object

In [27]:
df.loc[1]

KeyError: 1

In [28]:
df.iloc[1]

Name        Bob
Age          30
City    Chennai
Name: rec_2, dtype: object

In [30]:
df

         Name  Age     City
rec_1     Abe   20      Hyd
rec_2     Bob   30  Chennai
rec_3  Charam   40      Blr

In [31]:
df[df["Age"]>25]

         Name  Age     City
rec_2     Bob   30  Chennai
rec_3  Charam   40      Blr

In [32]:
data = {
    'Std_id': [101, 102, 103, 104, 105],
    'Student': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    "Maths": [85, 90, 78, 92, 88],
    "Science": [80, 85, 82, 88, 90],
    "English": [78, 82, 85, 90, 87]
}

In [34]:
df = pd.DataFrame(data)

In [35]:
df

   Std_id  Student  Maths  Science  English
0     101    Alice     85       80       78
1     102      Bob     90       85       82
2     103  Charlie     78       82       85
3     104    David     92       88       90
4     105      Eve     88       90       87

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Std_id   5 non-null      int64
 1   Student  5 non-null      object
 2   Maths    5 non-null      int64
 3   Science  5 non-null      int64
 4   English  5 non-null      int64
dtypes: int64(4), object(1)
memory usage: 332.0+ bytes

In [37]:
df.describe()

           Std_id      Maths    Science    English
count    5.000000   5.000000   5.000000   5.000000
mean   103.000000  86.600000  85.000000  84.400000
std      1.581139   5.458938   4.123106   4.615192
min    101.000000  78.000000  80.000000  78.000000
25%    102.000000  85.000000  82.000000  82.000000
50%    103.000000  88.000000  85.000000  85.000000
75%    104.000000  90.000000  88.000000  87.000000
max    105.000000  92.000000  90.000000  90.000000

In [38]:
df

   Std_id  Student  Maths  Science  English
0     101    Alice     85       80       78
1     102      Bob     90       85       82
2     103  Charlie     78       82       85
3     104    David     92       88       90
4     105      Eve     88       90       87

In [39]:
df["Maths"]

0    85
1    90
2    78
3    92
4    88
Name: Maths, dtype: int64

In [40]:
df["Maths"].mean()

np.float64(86.6)

In [41]:
df

   Std_id  Student  Maths  Science  English
0     101    Alice     85       80       78
1     102      Bob     90       85       82
2     103  Charlie     78       82       85
3     104    David     92       88       90
4     105      Eve     88       90       87

In [42]:
df["Total_Marks"] = df["Maths"] + df["Science"] + df["English"]

In [43]:
df

   Std_id  Student  Maths  Science  English  Total_Marks
0     101    Alice     85       80       78          243
1     102      Bob     90       85       82          257
2     103  Charlie     78       82       85          245
3     104    David     92       88       90          270
4     105      Eve     88       90       87          265

In [44]:
df["Average"] = df["Total_Marks"] / 3

In [45]:
df

   Std_id  Student  Maths  Science  English  Total_Marks    Average
0     101    Alice     85       80       78          243  81.000000
1     102      Bob     90       85       82          257  85.666667
2     103  Charlie     78       82       85          245  81.666667
3     104    David     92       88       90          270  90.000000
4     105      Eve     88       90       87          265  88.333333

In [46]:
df[df["Average"] > 85 ]

   Std_id Student  Maths  Science  English  Total_Marks    Average
1     102     Bob     90       85       82          257  85.666667
3     104   David     92       88       90          270  90.000000
4     105     Eve     88       90       87          265  88.333333

In [49]:
avg_df = df[df["Average"] > 85 ]

In [50]:
avg_df.sort_values("Average")

   Std_id Student  Maths  Science  English  Total_Marks    Average
1     102     Bob     90       85       82          257  85.666667
4     105     Eve     88       90       87          265  88.333333
3     104   David     92       88       90          270  90.000000

In [51]:
df[df["Average"] > 85 ].sort_values("Average")

   Std_id Student  Maths  Science  English  Total_Marks    Average
1     102     Bob     90       85       82          257  85.666667
4     105     Eve     88       90       87          265  88.333333
3     104   David     92       88       90          270  90.000000

In [52]:
df

   Std_id  Student  Maths  Science  English  Total_Marks    Average
0     101    Alice     85       80       78          243  81.000000
1     102      Bob     90       85       82          257  85.666667
2     103  Charlie     78       82       85          245  81.666667
3     104    David     92       88       90          270  90.000000
4     105      Eve     88       90       87          265  88.333333

In [53]:
def assign_grade(avg):
    if avg >= 90:
        return "A"
    elif avg >= 80:
        return "B"
    else: 
        return "C"

In [54]:
df["Grade"] = df["Average"].apply(assign_grade)

In [55]:
df

   Std_id  Student  Maths  Science  English  Total_Marks    Average Grade
0     101    Alice     85       80       78          243  81.000000     B
1     102      Bob     90       85       82          257  85.666667     B
2     103  Charlie     78       82       85          245  81.666667     B
3     104    David     92       88       90          270  90.000000     A
4     105      Eve     88       90       87          265  88.333333     B

In [56]:
df

   Std_id  Student  Maths  Science  English  Total_Marks    Average Grade
0     101    Alice     85       80       78          243  81.000000     B
1     102      Bob     90       85       82          257  85.666667     B
2     103  Charlie     78       82       85          245  81.666667     B
3     104    David     92       88       90          270  90.000000     A
4     105      Eve     88       90       87          265  88.333333     B

In [57]:
df.to_csv("student_marks.csv")

In [58]:
df.to_csv("student_marks.csv",index=False)

In [60]:
del df["Grade"]

In [61]:
df

   Std_id  Student  Maths  Science  English  Total_Marks    Average
0     101    Alice     85       80       78          243  81.000000
1     102      Bob     90       85       82          257  85.666667
2     103  Charlie     78       82       85          245  81.666667
3     104    David     92       88       90          270  90.000000
4     105      Eve     88       90       87          265  88.333333

In [62]:
df["Resul"] = df["Average"].apply( lambda x:  "Pass" if x>=85 else "Fail"    )

In [63]:
df

   Std_id  Student  Maths  Science  English  Total_Marks    Average Resul
0     101    Alice     85       80       78          243  81.000000  Fail
1     102      Bob     90       85       82          257  85.666667  Pass
2     103  Charlie     78       82       85          245  81.666667  Fail
3     104    David     92       88       90          270  90.000000  Pass
4     105      Eve     88       90       87          265  88.333333  Pass

In [64]:
del df["Resul"]

In [65]:
df

   Std_id  Student  Maths  Science  English  Total_Marks    Average
0     101    Alice     85       80       78          243  81.000000
1     102      Bob     90       85       82          257  85.666667
2     103  Charlie     78       82       85          245  81.666667
3     104    David     92       88       90          270  90.000000
4     105      Eve     88       90       87          265  88.333333

In [68]:
def check_pass(row): 
    if row["Maths"] >= 85 and row["Science"] >= 80 and row["English"] >= 80: 
        return "Pass"
    else: 
        return "Fail"

In [73]:
df["Res"] = df.apply(check_pass, axis=1 )

In [74]:
df

   Std_id  Student  Maths  Science  English  Total_Marks    Average   Res
0     101    Alice     85       80       78          243  81.000000  Fail
1     102      Bob     90       85       82          257  85.666667  Pass
2     103  Charlie     78       82       85          245  81.666667  Fail
3     104    David     92       88       90          270  90.000000  Pass
4     105      Eve     88       90       87          265  88.333333  Pass

In [72]:
df

   Std_id  Student  Maths  Science  English  Total_Marks    Average
0     101    Alice     85       80       78          243  81.000000
1     102      Bob     90       85       82          257  85.666667
2     103  Charlie     78       82       85          245  81.666667
3     104    David     92       88       90          270  90.000000
4     105      Eve     88       90       87          265  88.333333

In [71]:
df['Maths'].sum()

np.int64(433)

In [81]:
df['Maths'].apply(sum)  #  df['Maths']  this is series

TypeError: 'int' object is not iterable

In [82]:
df[['Maths']].apply(sum)

Maths    433
dtype: int64

In [83]:
df['Maths'].sum()

np.int64(433)

In [84]:
df

   Std_id  Student  Maths  Science  English  Total_Marks    Average   Res
0     101    Alice     85       80       78          243  81.000000  Fail
1     102      Bob     90       85       82          257  85.666667  Pass
2     103  Charlie     78       82       85          245  81.666667  Fail
3     104    David     92       88       90          270  90.000000  Pass
4     105      Eve     88       90       87          265  88.333333  Pass

In [85]:
df["Grade"] = df["Average"].apply(assign_grade)

In [86]:
df

,Std_id,Student,Maths,Science,English,Total_Marks,Average,Res,Grade
0,101,Alice,85,80,78,243,81.000000,Fail,B
1,102,Bob,90,85,82,257,85.666667,Pass,B
2,103,Charlie,78,82,85,245,81.666667,Fail,B
3,104,David,92,88,90,270,90.000000,Pass,A
4,105,Eve,88,90,87,265,88.333333,Pass,B

In [87]:
# map 
grade_nums = {"A":1, "B":2, "C":3}

In [88]:
df["Grade_Num"] = df['Grade'].map(grade_nums)

In [89]:
df

,Std_id,Student,Maths,Science,English,Total_Marks,Average,Res,Grade,Grade_Num
0,101,Alice,85,80,78,243,81.000000,Fail,B,2
1,102,Bob,90,85,82,257,85.666667,Pass,B,2
2,103,Charlie,78,82,85,245,81.666667,Fail,B,2
3,104,David,92,88,90,270,90.000000,Pass,A,1
4,105,Eve,88,90,87,265,88.333333,Pass,B,2

In [90]:
# df["Resul"] = df["Average"].apply( lambda x:  "Pass" if x>=85 else "Fail"    )

In [91]:
def res_def(avg):
    if avg >= 85: 
        return "Pass"
    else: 
        return "Fail"

In [92]:
df["Res_Map"] = df["Average"].map(res_def)

In [93]:
df

,Std_id,Student,Maths,Science,English,Total_Marks,Average,Res,Grade,Grade_Num,Res_Map
0,101,Alice,85,80,78,243,81.000000,Fail,B,2,Fail
1,102,Bob,90,85,82,257,85.666667,Pass,B,2,Pass
2,103,Charlie,78,82,85,245,81.666667,Fail,B,2,Fail
3,104,David,92,88,90,270,90.000000,Pass,A,1,Pass
4,105,Eve,88,90,87,265,88.333333,Pass,B,2,Pass

In [95]:
df["Category"] = df["Average"].map(  lambda x: "Topper" if x>85 else "Regular"    )

In [96]:
df

,Std_id,Student,Maths,Science,English,Total_Marks,Average,Res,Grade,Grade_Num,Res_Map,Category
0,101,Alice,85,80,78,243,81.000000,Fail,B,2,Fail,Regular
1,102,Bob,90,85,82,257,85.666667,Pass,B,2,Pass,Topper
2,103,Charlie,78,82,85,245,81.666667,Fail,B,2,Fail,Regular
3,104,David,92,88,90,270,90.000000,Pass,A,1,Pass,Topper
4,105,Eve,88,90,87,265,88.333333,Pass,B,2,Pass,Topper