In [1]:
# Pandas   --> Data Structures

In [2]:
# Series          -->  1-D labeled array 
# DataFrame       -->  2-D labeled array

In [3]:
import pandas as pd

In [4]:
nums = [10,20,30,40]

In [5]:
s = pd.Series(nums)

In [6]:
s

0    10
1    20
2    30
3    40
dtype: int64

In [7]:
s = pd.Series([1,2,3,4],index=['a','b','c','d'])

In [8]:
s

a    1
b    2
c    3
d    4
dtype: int64

In [9]:
d = {"Abe":"US","Bob":"Canada","Charan":"India"}

In [10]:
d

{'Abe': 'US', 'Bob': 'Canada', 'Charan': 'India'}

In [11]:
s = pd.Series(d)

In [12]:
s

Abe           US
Bob       Canada
Charan     India
dtype: object

In [13]:
s.values

array(['US', 'Canada', 'India'], dtype=object)

In [14]:
s.index

Index(['Abe', 'Bob', 'Charan'], dtype='object')

In [15]:
s.dtype

dtype('O')

In [16]:
s = pd.Series([10,20,30])

In [17]:
s+10

0    20
1    30
2    40
dtype: int64

In [18]:
s*2

0    20
1    40
2    60
dtype: int64

In [21]:
s

0    10
1    20
2    30
dtype: int64

In [22]:
s[s>10]

1    20
2    30
dtype: int64

In [26]:
df = pd.DataFrame({"Name":["Abe","Bob","Charam"],"Age":[20,30,40],"City":["Hyd","Chennai","Blr"]})

In [25]:
df   #  Columns Labels  | Rows  Index

     name  Age     City
0     Abe   20      Hyd
1     Bob   30  Chennai
2  Charam   40      Blr

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame({"Name":["Abe","Bob","Charam"],"Age":[20,30,40],"City":["Hyd","Chennai","Blr"]}, index=["rec_1","rec_2","rec_3"])

In [4]:
df

         Name  Age     City
rec_1     Abe   20      Hyd
rec_2     Bob   30  Chennai
rec_3  Charam   40      Blr

In [28]:
data = [{"name":"A","Salary":10000},{"name":"B","Salary":20000} ]

In [29]:
df = pd.DataFrame(data)

In [30]:
df

  name  Salary
0    A   10000
1    B   20000

In [31]:
data = [{"name":"A","Salary":10000},{"name":"B","Salary":20000, "City":"Hyd"} ]

In [33]:
df = pd.DataFrame(data)

In [34]:
df

  name  Salary City
0    A   10000  NaN
1    B   20000  Hyd

In [35]:
df.shape

(2, 3)

In [36]:
df.columns

Index(['name', 'Salary', 'City'], dtype='object')

In [5]:
df.index

Index(['rec_1', 'rec_2', 'rec_3'], dtype='object')

In [39]:
df.dtypes

name      object
Salary     int64
City      object
dtype: object

In [40]:
df

  name  Salary City
0    A   10000  NaN
1    B   20000  Hyd

In [41]:
df["Salary"]

0    10000
1    20000
Name: Salary, dtype: int64

In [42]:
type(df["Salary"])

pandas.core.series.Series

In [43]:
type(df)

pandas.core.frame.DataFrame

In [44]:
sal_series = pd.Series([1000,2000,3000])

In [46]:
type(sal_series)

pandas.core.series.Series

In [47]:
sal_series.to_frame(name="Salary")

   Salary
0    1000
1    2000
2    3000

In [48]:
df

  name  Salary City
0    A   10000  NaN
1    B   20000  Hyd

In [49]:
df["Salary"]   # Series

0    10000
1    20000
Name: Salary, dtype: int64

In [50]:
df

  name  Salary City
0    A   10000  NaN
1    B   20000  Hyd

In [51]:
df['City']

0    NaN
1    Hyd
Name: City, dtype: object

In [52]:
df[0]

KeyError: 0

In [53]:
df

  name  Salary City
0    A   10000  NaN
1    B   20000  Hyd

In [54]:
df.loc[0]

name          A
Salary    10000
City        NaN
Name: 0, dtype: object

In [55]:
df.loc[0,"Salary"]

np.int64(10000)

In [56]:
s1 = pd.Series([10,20],index=["A","B"])
s2 = pd.Series([20,30],index=["B","C"])

In [57]:
s1

A    10
B    20
dtype: int64

In [59]:
s2

B    20
C    30
dtype: int64

In [61]:
s1+s2   #  Alignment is happenning using Index

A     NaN
B    40.0
C     NaN
dtype: float64

In [63]:
df1 = pd.DataFrame({"A":[10,20,30],"B":[15,25,35]})

In [64]:
df1

    A   B
0  10  15
1  20  25
2  30  35

In [65]:
df2 = pd.DataFrame({"A":[9,15,25],"B":[10,15,25]})

In [66]:
df2

    A   B
0   9  10
1  15  15
2  25  25

In [68]:
df1+df2    #  Allignment will happen using rows and columns

    A   B
0  19  25
1  35  40
2  55  60

In [69]:
df

  name  Salary City
0    A   10000  NaN
1    B   20000  Hyd

In [70]:
df.isna()

    name  Salary   City
0  False   False   True
1  False   False  False

In [72]:
df.fillna("No City")

  name  Salary     City
0    A   10000  No City
1    B   20000      Hyd

In [73]:
df

  name  Salary City
0    A   10000  NaN
1    B   20000  Hyd

In [74]:
df.dropna()

  name  Salary City
1    B   20000  Hyd

In [80]:
orders_df = pd.DataFrame({"Order_id": [1, 2, 3, 4, 5],
                       "Customer_id": [101, 102, 101, 103, 101],
                       "Product": ["A", "B", "C", "D", "A"],
                       "Price": [10.0, 20.0, 15.0, 25.0, 35.0],
                       "Status": ["Shipped", "Pending", "Delivered", "Shipped", "Delivered"]})

In [81]:
orders_df

   Order_id  Customer_id Product  Price     Status
0         1          101       A   10.0    Shipped
1         2          102       B   20.0    Pending
2         3          101       C   15.0  Delivered
3         4          103       D   25.0    Shipped
4         5          101       A   35.0  Delivered

In [82]:
orders_df["Status"]

0      Shipped
1      Pending
2    Delivered
3      Shipped
4    Delivered
Name: Status, dtype: object

In [83]:
orders_df[orders_df["Status"] == "Delivered"]

   Order_id  Customer_id Product  Price     Status
2         3          101       C   15.0  Delivered
4         5          101       A   35.0  Delivered

In [84]:
orders_df[orders_df["Status"] == "Delivered"]["Price"]

2    15.0
4    35.0
Name: Price, dtype: float64

In [85]:
orders_df[orders_df["Status"] == "Delivered"]["Price"].sum()

np.float64(50.0)

In [86]:
orders_df[orders_df["Status"] == "Pending"]

   Order_id  Customer_id Product  Price   Status
1         2          102       B   20.0  Pending

In [87]:
orders_df = pd.read_csv("order.csv")

In [88]:
orders_df

,order_id,customer_name,product,quantity,price,order_date,status
0,1001,John Smith,Laptop,1,999.99,2025-01-15,Completed
1,1002,Sarah Johnson,Mouse,5,29.99,2025-01-16,Completed
2,1003,Mike Davis,Keyboard,2,79.99,2025-01-17,Pending
3,1004,Emma Wilson,Monitor,1,349.99,2025-01-18,Shipped
4,1005,James Brown,Headphones,3,149.99,2025-01-19,Completed
5,1006,Lisa Anderson,USB Cable,10,9.99,2025-01-20,Pending
6,1007,Robert Taylor,Webcam,2,89.99,2025-01-21,Completed
7,1008,Jennifer White,SSD 1TB,4,119.99,2025-01-22,Shipped
8,1009,David Martinez,RAM 16GB,1,159.99,2025-01-23,Pending
9,1010,Michelle Lee,Power Bank,6,39.99,2025-01-24,Completed
10,1011,Chris Garcia,Speaker,2,199.99,2025-01-25,Shipped
11,1012,Amanda Rodriguez,Desk Lamp,1,49.99,2025-01-26,Completed
12,1013,Kevin Miller,Phone Stand,8,19.99,2025-01-27,Pending
13,1014,Jessica Davis,External HDD 2TB,3,79.99,2025-01-28,Completed
14,1015,Brandon Wilson,Monitor Stand,2,59.99,2025-01-29,Shipped

In [89]:
orders_df[orders_df["status"] == 'Completed']   #  select * from order where status = 'Completed'

,order_id,customer_name,product,quantity,price,order_date,status
0,1001,John Smith,Laptop,1,999.99,2025-01-15,Completed
1,1002,Sarah Johnson,Mouse,5,29.99,2025-01-16,Completed
4,1005,James Brown,Headphones,3,149.99,2025-01-19,Completed
6,1007,Robert Taylor,Webcam,2,89.99,2025-01-21,Completed
9,1010,Michelle Lee,Power Bank,6,39.99,2025-01-24,Completed
11,1012,Amanda Rodriguez,Desk Lamp,1,49.99,2025-01-26,Completed
13,1014,Jessica Davis,External HDD 2TB,3,79.99,2025-01-28,Completed

In [91]:
orders_df[orders_df["status"] == 'Completed']['price'].sum()   # select sum(price) from orders where status = 'Completed'

np.float64(1439.93)

In [92]:
orders_df["total_price"] = orders_df["quantity"] * orders_df["price"]

In [93]:
orders_df

,order_id,customer_name,product,quantity,price,order_date,status,total_price
0,1001,John Smith,Laptop,1,999.99,2025-01-15,Completed,999.99
1,1002,Sarah Johnson,Mouse,5,29.99,2025-01-16,Completed,149.95
2,1003,Mike Davis,Keyboard,2,79.99,2025-01-17,Pending,159.98
3,1004,Emma Wilson,Monitor,1,349.99,2025-01-18,Shipped,349.99
4,1005,James Brown,Headphones,3,149.99,2025-01-19,Completed,449.97
5,1006,Lisa Anderson,USB Cable,10,9.99,2025-01-20,Pending,99.90
6,1007,Robert Taylor,Webcam,2,89.99,2025-01-21,Completed,179.98
7,1008,Jennifer White,SSD 1TB,4,119.99,2025-01-22,Shipped,479.96
8,1009,David Martinez,RAM 16GB,1,159.99,2025-01-23,Pending,159.99
9,1010,Michelle Lee,Power Bank,6,39.99,2025-01-24,Completed,239.94
10,1011,Chris Garcia,Speaker,2,199.99,2025-01-25,Shipped,399.98
11,1012,Amanda Rodriguez,Desk Lamp,1,49.99,2025-01-26,Completed,49.99
12,1013,Kevin Miller,Phone Stand,8,19.99,2025-01-27,Pending,159.92
13,1014,Jessica Davis,External HDD 2TB,3,79.99,2025-01-28,Completed,239.97
14,1015,Brandon Wilson,Monitor Stand,2,59.99,2025-01-29,Shipped,119.98

In [94]:
orders_df[orders_df["status"] == 'Completed']['total_price'].sum()

np.float64(2309.79)

In [95]:
orders_df[orders_df["status"] == 'Completed']['total_price'].mean()

np.float64(329.96999999999997)

In [97]:
orders_df[orders_df["status"] == 'Completed']['order_id'].count()

np.int64(7)

In [98]:
orders_df

,order_id,customer_name,product,quantity,price,order_date,status,total_price
0,1001,John Smith,Laptop,1,999.99,2025-01-15,Completed,999.99
1,1002,Sarah Johnson,Mouse,5,29.99,2025-01-16,Completed,149.95
2,1003,Mike Davis,Keyboard,2,79.99,2025-01-17,Pending,159.98
3,1004,Emma Wilson,Monitor,1,349.99,2025-01-18,Shipped,349.99
4,1005,James Brown,Headphones,3,149.99,2025-01-19,Completed,449.97
5,1006,Lisa Anderson,USB Cable,10,9.99,2025-01-20,Pending,99.90
6,1007,Robert Taylor,Webcam,2,89.99,2025-01-21,Completed,179.98
7,1008,Jennifer White,SSD 1TB,4,119.99,2025-01-22,Shipped,479.96
8,1009,David Martinez,RAM 16GB,1,159.99,2025-01-23,Pending,159.99
9,1010,Michelle Lee,Power Bank,6,39.99,2025-01-24,Completed,239.94
10,1011,Chris Garcia,Speaker,2,199.99,2025-01-25,Shipped,399.98
11,1012,Amanda Rodriguez,Desk Lamp,1,49.99,2025-01-26,Completed,49.99
12,1013,Kevin Miller,Phone Stand,8,19.99,2025-01-27,Pending,159.92
13,1014,Jessica Davis,External HDD 2TB,3,79.99,2025-01-28,Completed,239.97
14,1015,Brandon Wilson,Monitor Stand,2,59.99,2025-01-29,Shipped,119.98

In [99]:
['total_price_tax'] = orders_df['total_price'] * 1.18

In [100]:
 orders_df

,order_id,customer_name,product,quantity,price,order_date,status,total_price,total_price_tax
0,1001,John Smith,Laptop,1,999.99,2025-01-15,Completed,999.99,1179.9882
1,1002,Sarah Johnson,Mouse,5,29.99,2025-01-16,Completed,149.95,176.9410
2,1003,Mike Davis,Keyboard,2,79.99,2025-01-17,Pending,159.98,188.7764
3,1004,Emma Wilson,Monitor,1,349.99,2025-01-18,Shipped,349.99,412.9882
4,1005,James Brown,Headphones,3,149.99,2025-01-19,Completed,449.97,530.9646
5,1006,Lisa Anderson,USB Cable,10,9.99,2025-01-20,Pending,99.90,117.8820
6,1007,Robert Taylor,Webcam,2,89.99,2025-01-21,Completed,179.98,212.3764
7,1008,Jennifer White,SSD 1TB,4,119.99,2025-01-22,Shipped,479.96,566.3528
8,1009,David Martinez,RAM 16GB,1,159.99,2025-01-23,Pending,159.99,188.7882
9,1010,Michelle Lee,Power Bank,6,39.99,2025-01-24,Completed,239.94,283.1292
10,1011,Chris Garcia,Speaker,2,199.99,2025-01-25,Shipped,399.98,471.9764
11,1012,Amanda Rodriguez,Desk Lamp,1,49.99,2025-01-26,Completed,49.99,58.9882
12,1013,Kevin Miller,Phone Stand,8,19.99,2025-01-27,Pending,159.92,188.7056
13,1014,Jessica Davis,External HDD 2TB,3,79.99,2025-01-28,Completed,239.97,283.1646
14,1015,Brandon Wilson,Monitor Stand,2,59.99,2025-01-29,Shipped,119.98,141.5764