In [1]:
import snowflake.connector

In [11]:
conn = snowflake.connector.connect(
    user='detrainings01'
    , password='DataEngineering@2026'
    , account='sqqpjbk-pi02317'
    , warehouse='COMPUTE_WH'
    , role='SYSADMIN'
    , database='MY_DB1'
    , schema='RAW'
)

In [12]:
cur = conn.cursor()
cur.execute("SELECT CURRENT_VERSION()")
one_row = cur.fetchone()
print(one_row[0])

10.6.2

In [13]:
cur.execute("CREATE OR REPLACE TABLE EMPLOYEES (ID INT, NAME VARCHAR, SALARY INT)")

In [14]:
cur.execute("INSERT INTO EMPLOYEES VALUES (1,'JOHN',10000), (2,'MARY',20000)")

In [15]:
cur.execute("SELECT * FROM EMPLOYEES")

In [16]:
res = cur.fetchall()

In [17]:
res

[(1, 'JOHN', 10000), (2, 'MARY', 20000)]

In [18]:
for row in res:  
    print(row)

(1, 'JOHN', 10000)
(2, 'MARY', 20000)

In [19]:
emp_id = 1 
cur.execute(f"SELECT * FROM EMPLOYEES WHERE  ID = {emp_id}")

In [20]:
res = cur.fetchall()

In [21]:
res

[(1, 'JOHN', 10000)]

In [22]:
import pandas as  pd

In [23]:
query = "SELECT * FROM EMPLOYEES"

In [24]:
df = pd.read_sql(query,conn)

C:\Users\Chinna\AppData\Local\Temp\ipykernel_12156\785092515.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query,conn)

In [25]:
df

   ID  NAME  SALARY
0   1  JOHN   10000
1   2  MARY   20000

In [26]:
new_df = pd.DataFrame({"ID":[3,4], "NAME":["Alice","Bob"], "SALARY":[12000, 15000]})

In [27]:
new_df

   ID   NAME  SALARY
0   3  Alice   12000
1   4    Bob   15000

In [28]:
from snowflake.connector.pandas_tools import write_pandas

In [29]:
write_pandas(conn, new_df, "EMPLOYEES")

(True,
 1,
 2,
 [('snowpark_temp_stage_b44g8hpvv2/file0.txt',
   'LOADED',
   2,
   2,
   1,
   0,
   None,
   None,
   None,
   None)])

In [38]:
cur.execute("SELECT count(*) FROM EMPLOYEES")

In [39]:
cur.fetchall()[0]

(4,)

In [40]:
# File Name Based Incremental Loading

In [41]:
from datetime import date

In [44]:
today = date.today().strftime("%Y%m%d")

In [45]:
today

'20260228'

In [51]:
query = f"""COPY INTO ORDERS 
FROM @orders_stage/
FILES = ('orders_{today}.csv.gz')
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 ) ;"""

In [52]:
query

"COPY INTO ORDERS \nFROM @orders_stage/\nFILES = ('orders_20260228.csv.gz')\nFILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 ) ;"

In [53]:
cur.execute(query)

In [ ]:
cur.execute("SELECT current_database(), current_user, inet_server_port();")