In [7]:
import os
import csv
import json
import sqlite3
import requests
import pandas as pd
from pathlib import Path
from datetime import datetime

In [8]:
RAW       = Path("data/raw")
PROCESSED = Path("data/processed")
RAW.mkdir(parents=True, exist_ok=True)
PROCESSED.mkdir(parents=True, exist_ok=True)

In [9]:
print("\n" + "="*60)
print("  SECTION 1 — FILE INGESTION")
print("="*60)

============================================================
  SECTION 1 — FILE INGESTION
============================================================

In [10]:
customers = [
    ["customer_id", "name",           "email",              "city",        "tier"  ],
    [1,             "Alice Johnson",  "alice@email.com",    "New York",    "Gold"  ],
    [2,             "Bob Smith",      "bob@email.com",      "Chicago",     "Silver"],
    [3,             "Carol White",    "carol@email.com",    "Los Angeles", "Gold"  ],
    [4,             "David Lee",      "david@email.com",    "Houston",     "Bronze"],
    [5,             "Eva Brown",      "eva@email.com",      "Phoenix",     "Silver"],
]

In [11]:
with open(RAW / "customers.csv", "w", newline="") as f:
    csv.writer(f).writerows(customers)
print("Created: customers.csv")

Created: customers.csv

In [12]:
orders = [
    {"order_id": 101, "customer_id": 1, "product": "Laptop",  "qty": 1, "price": 999.99, "status": "delivered"},
    {"order_id": 102, "customer_id": 2, "product": "Mouse",   "qty": 2, "price":  25.00, "status": "shipped"  },
    {"order_id": 103, "customer_id": 3, "product": "Monitor", "qty": 1, "price": 349.99, "status": "pending"  },
    {"order_id": 104, "customer_id": 1, "product": "Keyboard","qty": 1, "price":  79.99, "status": "delivered"},
    {"order_id": 105, "customer_id": 5, "product": "Webcam",  "qty": 1, "price":  89.99, "status": "shipped"  },
]

In [13]:
with open(RAW / "orders.json", "w") as f:
    json.dump(orders, f, indent=2)
print("Created: orders.json")

Created: orders.json

In [14]:
products_df   = pd.DataFrame({
    "product_id": [1, 2, 3, 4, 5],
    "name":       ["Laptop", "Mouse", "Monitor", "Keyboard", "Webcam"],
    "price":      [999.99, 25.00, 349.99, 79.99, 89.99],
    "stock":      [50, 200, 75, 150, 120],
})

In [15]:
categories_df = pd.DataFrame({
    "category_id":   [1],
    "category_name": ["Electronics"],
})

In [17]:
!pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [18]:
with pd.ExcelWriter(RAW / "products.xlsx", engine="openpyxl") as writer:
    products_df.to_excel(writer,   sheet_name="Products",   index=False)
    categories_df.to_excel(writer, sheet_name="Categories", index=False)
print("Created: products.xlsx  (2 sheets)")

Created: products.xlsx  (2 sheets)

In [19]:
print("\n--- Reading customers.csv ---")
df_customers = pd.read_csv(RAW / "customers.csv")
print(df_customers)

--- Reading customers.csv ---
   customer_id           name            email         city    tier
0            1  Alice Johnson  alice@email.com     New York    Gold
1            2      Bob Smith    bob@email.com      Chicago  Silver
2            3    Carol White  carol@email.com  Los Angeles    Gold
3            4      David Lee  david@email.com      Houston  Bronze
4            5      Eva Brown    eva@email.com      Phoenix  Silver

In [20]:
print("\n--- Reading orders.json ---")
with open(RAW / "orders.json") as f:
    raw = json.load(f)
df_orders = pd.DataFrame(raw)
print(df_orders)

--- Reading orders.json ---
   order_id  customer_id   product  qty   price     status
0       101            1    Laptop    1  999.99  delivered
1       102            2     Mouse    2   25.00    shipped
2       103            3   Monitor    1  349.99    pending
3       104            1  Keyboard    1   79.99  delivered
4       105            5    Webcam    1   89.99    shipped

In [21]:
# Read Excel — sheet by name
print("\n--- Reading products.xlsx  (sheet=Products) ---")
df_products = pd.read_excel(RAW / "products.xlsx", sheet_name="Products")
print(df_products)

--- Reading products.xlsx  (sheet=Products) ---
   product_id      name   price  stock
0           1    Laptop  999.99     50
1           2     Mouse   25.00    200
2           3   Monitor  349.99     75
3           4  Keyboard   79.99    150
4           5    Webcam   89.99    120

In [22]:
print("\n--- Reading products.xlsx  (sheet=Categories) ---")
df_categories = pd.read_excel(RAW / "products.xlsx", sheet_name="Categories")
print(df_categories)

--- Reading products.xlsx  (sheet=Categories) ---
   category_id category_name
0            1   Electronics

In [23]:
print("\n" + "="*60)
print("  SECTION 2 — API INGESTION")
print("  https://jsonplaceholder.typicode.com")
print("="*60)

============================================================
  SECTION 2 — API INGESTION
  https://jsonplaceholder.typicode.com
============================================================

In [24]:
BASE_URL = "https://jsonplaceholder.typicode.com"

In [25]:
def api_get(endpoint, params=None):
    url = BASE_URL + endpoint
    for attempt in range(3):
        try:
            r = requests.get(url, params=params, timeout=10)
            r.raise_for_status()
            return r.json()
        except requests.RequestException as e:
            print(f"  Attempt {attempt+1} failed: {e}")
            if attempt == 2:
                raise
    return []

In [27]:
SAMPLE_USERS = [
    {"id":1,"name":"Leanne Graham","username":"Bret","email":"Sincere@april.biz",
     "phone":"1-770-736-0988","address":{"city":"Gwenborough"},"company":{"name":"Romaguera-Crona"}},
    {"id":2,"name":"Ervin Howell","username":"Antonette","email":"Shanna@melissa.tv",
     "phone":"010-692-6593","address":{"city":"Wisokyburgh"},"company":{"name":"Deckow-Crist"}},
    {"id":3,"name":"Clementine Bauch","username":"Samantha","email":"Nathan@yesenia.net",
     "phone":"1-463-123-4447","address":{"city":"McKenziehaven"},"company":{"name":"Romaguera-Jacobson"}},
    {"id":4,"name":"Patricia Lebsack","username":"Karianne","email":"Julianne.OConner@kory.org",
     "phone":"493-170-9623","address":{"city":"South Elvis"},"company":{"name":"Robel-Corkery"}},
    {"id":5,"name":"Chelsey Dietrich","username":"Kamren","email":"Lucio_Hettinger@annie.ca",
     "phone":"(254)954-1289","address":{"city":"Roscoeview"},"company":{"name":"Keebler LLC"}},
]

In [28]:
SAMPLE_POSTS = [
    {"userId":1,"id":1,"title":"sunt aut facere repellat","body":"quia et suscipit recusandae"},
    {"userId":1,"id":2,"title":"qui est esse","body":"est rerum tempore vitae sequi"},
    {"userId":2,"id":3,"title":"ea molestias quasi exercitationem","body":"et iusto sed quo iure"},
    {"userId":2,"id":4,"title":"eum et est occaecati","body":"ullam et saepe reiciendis"},
    {"userId":3,"id":5,"title":"nesciunt quas odio","body":"repudiandae veniam quaerat"},
]

In [29]:
SAMPLE_COMMENTS = [
    {"postId":1,"id":1,"name":"id labore ex et quam laborum","email":"Eliseo@gardner.biz","body":"laudantium enim quasi est"},
    {"postId":1,"id":2,"name":"quo vero reiciendis velit similique earum","email":"Jayne_Kuhic@sydney.com","body":"est natus enim nihil est dolore"},
    {"postId":1,"id":3,"name":"odio adipisci rerum aut animi","email":"Nikita@garfield.biz","body":"quia molestiae reprehenderit quasi"},
]

In [30]:
print("\n--- Fetching /users ---")

--- Fetching /users ---

In [31]:
try:
    users_raw = api_get("/users")
    print("  (live API)")
except Exception:
    users_raw = SAMPLE_USERS
    print("  (network unavailable — using sample data)")

  (live API)

In [32]:
users_raw

[{'id': 1,
  'name': 'Leanne Graham',
  'username': 'Bret',
  'email': 'Sincere@april.biz',
  'address': {'street': 'Kulas Light',
   'suite': 'Apt. 556',
   'city': 'Gwenborough',
   'zipcode': '92998-3874',
   'geo': {'lat': '-37.3159', 'lng': '81.1496'}},
  'phone': '1-770-736-8031 x56442',
  'website': 'hildegard.org',
  'company': {'name': 'Romaguera-Crona',
   'catchPhrase': 'Multi-layered client-server neural-net',
   'bs': 'harness real-time e-markets'}},
 {'id': 2,
  'name': 'Ervin Howell',
  'username': 'Antonette',
  'email': 'Shanna@melissa.tv',
  'address': {'street': 'Victor Plains',
   'suite': 'Suite 879',
   'city': 'Wisokyburgh',
   'zipcode': '90566-7771',
   'geo': {'lat': '-43.9509', 'lng': '-34.4618'}},
  'phone': '010-692-6593 x09125',
  'website': 'anastasia.net',
  'company': {'name': 'Deckow-Crist',
   'catchPhrase': 'Proactive didactic contingency',
   'bs': 'synergize scalable supply-chains'}},
 {'id': 3,
  'name': 'Clementine Bauch',
  'username': 'Samantha',
  'email': 'Nathan@yesenia.net',
  'address': {'street': 'Douglas Extension',
   'suite': 'Suite 847',
   'city': 'McKenziehaven',
   'zipcode': '59590-4157',
   'geo': {'lat': '-68.6102', 'lng': '-47.0653'}},
  'phone': '1-463-123-4447',
  'website': 'ramiro.info',
  'company': {'name': 'Romaguera-Jacobson',
   'catchPhrase': 'Face to face bifurcated interface',
   'bs': 'e-enable strategic applications'}},
 {'id': 4,
  'name': 'Patricia Lebsack',
  'username': 'Karianne',
  'email': 'Julianne.OConner@kory.org',
  'address': {'street': 'Hoeger Mall',
   'suite': 'Apt. 692',
   'city': 'South Elvis',
   'zipcode': '53919-4257',
   'geo': {'lat': '29.4572', 'lng': '-164.2990'}},
  'phone': '493-170-9623 x156',
  'website': 'kale.biz',
  'company': {'name': 'Robel-Corkery',
   'catchPhrase': 'Multi-tiered zero tolerance productivity',
   'bs': 'transition cutting-edge web services'}},
 {'id': 5,
  'name': 'Chelsey Dietrich',
  'username': 'Kamren',
  'email': 'Lucio_Hettinger@annie.ca',
  'address': {'street': 'Skiles Walks',
   'suite': 'Suite 351',
   'city': 'Roscoeview',
   'zipcode': '33263',
   'geo': {'lat': '-31.8129', 'lng': '62.5342'}},
  'phone': '(254)954-1289',
  'website': 'demarco.info',
  'company': {'name': 'Keebler LLC',
   'catchPhrase': 'User-centric fault-tolerant solution',
   'bs': 'revolutionize end-to-end systems'}},
 {'id': 6,
  'name': 'Mrs. Dennis Schulist',
  'username': 'Leopoldo_Corkery',
  'email': 'Karley_Dach@jasper.info',
  'address': {'street': 'Norberto Crossing',
   'suite': 'Apt. 950',
   'city': 'South Christy',
   'zipcode': '23505-1337',
   'geo': {'lat': '-71.4197', 'lng': '71.7478'}},
  'phone': '1-477-935-8478 x6430',
  'website': 'ola.org',
  'company': {'name': 'Considine-Lockman',
   'catchPhrase': 'Synchronised bottom-line interface',
   'bs': 'e-enable innovative applications'}},
 {'id': 7,
  'name': 'Kurtis Weissnat',
  'username': 'Elwyn.Skiles',
  'email': 'Telly.Hoeger@billy.biz',
  'address': {'street': 'Rex Trail',
   'suite': 'Suite 280',
   'city': 'Howemouth',
   'zipcode': '58804-1099',
   'geo': {'lat': '24.8918', 'lng': '21.8984'}},
  'phone': '210.067.6132',
  'website': 'elvis.io',
  'company': {'name': 'Johns Group',
   'catchPhrase': 'Configurable multimedia task-force',
   'bs': 'generate enterprise e-tailers'}},
 {'id': 8,
  'name': 'Nicholas Runolfsdottir V',
  'username': 'Maxime_Nienow',
  'email': 'Sherwood@rosamond.me',
  'address': {'street': 'Ellsworth Summit',
   'suite': 'Suite 729',
   'city': 'Aliyaview',
   'zipcode': '45169',
   'geo': {'lat': '-14.3990', 'lng': '-120.7677'}},
  'phone': '586.493.6943 x140',
  'website': 'jacynthe.com',
  'company': {'name': 'Abernathy Group',
   'catchPhrase': 'Implemented secondary concept',
   'bs': 'e-enable extensible e-tailers'}},
 {'id': 9,
  'name': 'Glenna Reichert',
  'username': 'Delphine',
  'email': 'Chaim_McDermott@dana.io',
  'address': {'street': 'Dayna Park',
   'suite': 'Suite 449',
   'city': 'Bartholomebury',
   'zipcode': '76495-3109',
   'geo': {'lat': '24.6463', 'lng': '-168.8889'}},
  'phone': '(775)976-6794 x41206',
  'website': 'conrad.com',
  'company': {'name': 'Yost and Sons',
   'catchPhrase': 'Switchable contextually-based project',
   'bs': 'aggregate real-time technologies'}},
 {'id': 10,
  'name': 'Clementina DuBuque',
  'username': 'Moriah.Stanton',
  'email': 'Rey.Padberg@karina.biz',
  'address': {'street': 'Kattie Turnpike',
   'suite': 'Suite 198',
   'city': 'Lebsackbury',
   'zipcode': '31428-2261',
   'geo': {'lat': '-38.2386', 'lng': '57.2232'}},
  'phone': '024-648-3804',
  'website': 'ambrose.net',
  'company': {'name': 'Hoeger LLC',
   'catchPhrase': 'Centralized empowering task-force',
   'bs': 'target end-to-end models'}}]

In [36]:
df_users = pd.json_normalize(users_raw)

In [40]:
users_raw

[{'id': 1,
  'name': 'Leanne Graham',
  'username': 'Bret',
  'email': 'Sincere@april.biz',
  'address': {'street': 'Kulas Light',
   'suite': 'Apt. 556',
   'city': 'Gwenborough',
   'zipcode': '92998-3874',
   'geo': {'lat': '-37.3159', 'lng': '81.1496'}},
  'phone': '1-770-736-8031 x56442',
  'website': 'hildegard.org',
  'company': {'name': 'Romaguera-Crona',
   'catchPhrase': 'Multi-layered client-server neural-net',
   'bs': 'harness real-time e-markets'}},
 {'id': 2,
  'name': 'Ervin Howell',
  'username': 'Antonette',
  'email': 'Shanna@melissa.tv',
  'address': {'street': 'Victor Plains',
   'suite': 'Suite 879',
   'city': 'Wisokyburgh',
   'zipcode': '90566-7771',
   'geo': {'lat': '-43.9509', 'lng': '-34.4618'}},
  'phone': '010-692-6593 x09125',
  'website': 'anastasia.net',
  'company': {'name': 'Deckow-Crist',
   'catchPhrase': 'Proactive didactic contingency',
   'bs': 'synergize scalable supply-chains'}},
 {'id': 3,
  'name': 'Clementine Bauch',
  'username': 'Samantha',
  'email': 'Nathan@yesenia.net',
  'address': {'street': 'Douglas Extension',
   'suite': 'Suite 847',
   'city': 'McKenziehaven',
   'zipcode': '59590-4157',
   'geo': {'lat': '-68.6102', 'lng': '-47.0653'}},
  'phone': '1-463-123-4447',
  'website': 'ramiro.info',
  'company': {'name': 'Romaguera-Jacobson',
   'catchPhrase': 'Face to face bifurcated interface',
   'bs': 'e-enable strategic applications'}},
 {'id': 4,
  'name': 'Patricia Lebsack',
  'username': 'Karianne',
  'email': 'Julianne.OConner@kory.org',
  'address': {'street': 'Hoeger Mall',
   'suite': 'Apt. 692',
   'city': 'South Elvis',
   'zipcode': '53919-4257',
   'geo': {'lat': '29.4572', 'lng': '-164.2990'}},
  'phone': '493-170-9623 x156',
  'website': 'kale.biz',
  'company': {'name': 'Robel-Corkery',
   'catchPhrase': 'Multi-tiered zero tolerance productivity',
   'bs': 'transition cutting-edge web services'}},
 {'id': 5,
  'name': 'Chelsey Dietrich',
  'username': 'Kamren',
  'email': 'Lucio_Hettinger@annie.ca',
  'address': {'street': 'Skiles Walks',
   'suite': 'Suite 351',
   'city': 'Roscoeview',
   'zipcode': '33263',
   'geo': {'lat': '-31.8129', 'lng': '62.5342'}},
  'phone': '(254)954-1289',
  'website': 'demarco.info',
  'company': {'name': 'Keebler LLC',
   'catchPhrase': 'User-centric fault-tolerant solution',
   'bs': 'revolutionize end-to-end systems'}},
 {'id': 6,
  'name': 'Mrs. Dennis Schulist',
  'username': 'Leopoldo_Corkery',
  'email': 'Karley_Dach@jasper.info',
  'address': {'street': 'Norberto Crossing',
   'suite': 'Apt. 950',
   'city': 'South Christy',
   'zipcode': '23505-1337',
   'geo': {'lat': '-71.4197', 'lng': '71.7478'}},
  'phone': '1-477-935-8478 x6430',
  'website': 'ola.org',
  'company': {'name': 'Considine-Lockman',
   'catchPhrase': 'Synchronised bottom-line interface',
   'bs': 'e-enable innovative applications'}},
 {'id': 7,
  'name': 'Kurtis Weissnat',
  'username': 'Elwyn.Skiles',
  'email': 'Telly.Hoeger@billy.biz',
  'address': {'street': 'Rex Trail',
   'suite': 'Suite 280',
   'city': 'Howemouth',
   'zipcode': '58804-1099',
   'geo': {'lat': '24.8918', 'lng': '21.8984'}},
  'phone': '210.067.6132',
  'website': 'elvis.io',
  'company': {'name': 'Johns Group',
   'catchPhrase': 'Configurable multimedia task-force',
   'bs': 'generate enterprise e-tailers'}},
 {'id': 8,
  'name': 'Nicholas Runolfsdottir V',
  'username': 'Maxime_Nienow',
  'email': 'Sherwood@rosamond.me',
  'address': {'street': 'Ellsworth Summit',
   'suite': 'Suite 729',
   'city': 'Aliyaview',
   'zipcode': '45169',
   'geo': {'lat': '-14.3990', 'lng': '-120.7677'}},
  'phone': '586.493.6943 x140',
  'website': 'jacynthe.com',
  'company': {'name': 'Abernathy Group',
   'catchPhrase': 'Implemented secondary concept',
   'bs': 'e-enable extensible e-tailers'}},
 {'id': 9,
  'name': 'Glenna Reichert',
  'username': 'Delphine',
  'email': 'Chaim_McDermott@dana.io',
  'address': {'street': 'Dayna Park',
   'suite': 'Suite 449',
   'city': 'Bartholomebury',
   'zipcode': '76495-3109',
   'geo': {'lat': '24.6463', 'lng': '-168.8889'}},
  'phone': '(775)976-6794 x41206',
  'website': 'conrad.com',
  'company': {'name': 'Yost and Sons',
   'catchPhrase': 'Switchable contextually-based project',
   'bs': 'aggregate real-time technologies'}},
 {'id': 10,
  'name': 'Clementina DuBuque',
  'username': 'Moriah.Stanton',
  'email': 'Rey.Padberg@karina.biz',
  'address': {'street': 'Kattie Turnpike',
   'suite': 'Suite 198',
   'city': 'Lebsackbury',
   'zipcode': '31428-2261',
   'geo': {'lat': '-38.2386', 'lng': '57.2232'}},
  'phone': '024-648-3804',
  'website': 'ambrose.net',
  'company': {'name': 'Hoeger LLC',
   'catchPhrase': 'Centralized empowering task-force',
   'bs': 'target end-to-end models'}}]

In [37]:
df_users

,id,name,username,email,phone,website,address.street,address.suite,address.city,address.zipcode,address.geo.lat,address.geo.lng,company.name,company.catchPhrase,company.bs
0,1,Leanne Graham,Bret,Sincere@april.biz,1-770-736-8031 x56442,hildegard.org,Kulas Light,Apt. 556,Gwenborough,92998-3874,-37.3159,81.1496,Romaguera-Crona,Multi-layered client-server neural-net,harness real-time e-markets
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,010-692-6593 x09125,anastasia.net,Victor Plains,Suite 879,Wisokyburgh,90566-7771,-43.9509,-34.4618,Deckow-Crist,Proactive didactic contingency,synergize scalable supply-chains
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,1-463-123-4447,ramiro.info,Douglas Extension,Suite 847,McKenziehaven,59590-4157,-68.6102,-47.0653,Romaguera-Jacobson,Face to face bifurcated interface,e-enable strategic applications
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,493-170-9623 x156,kale.biz,Hoeger Mall,Apt. 692,South Elvis,53919-4257,29.4572,-164.2990,Robel-Corkery,Multi-tiered zero tolerance productivity,transition cutting-edge web services
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,(254)954-1289,demarco.info,Skiles Walks,Suite 351,Roscoeview,33263,-31.8129,62.5342,Keebler LLC,User-centric fault-tolerant solution,revolutionize end-to-end systems
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,1-477-935-8478 x6430,ola.org,Norberto Crossing,Apt. 950,South Christy,23505-1337,-71.4197,71.7478,Considine-Lockman,Synchronised bottom-line interface,e-enable innovative applications
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,210.067.6132,elvis.io,Rex Trail,Suite 280,Howemouth,58804-1099,24.8918,21.8984,Johns Group,Configurable multimedia task-force,generate enterprise e-tailers
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,586.493.6943 x140,jacynthe.com,Ellsworth Summit,Suite 729,Aliyaview,45169,-14.3990,-120.7677,Abernathy Group,Implemented secondary concept,e-enable extensible e-tailers
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,(775)976-6794 x41206,conrad.com,Dayna Park,Suite 449,Bartholomebury,76495-3109,24.6463,-168.8889,Yost and Sons,Switchable contextually-based project,aggregate real-time technologies
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,024-648-3804,ambrose.net,Kattie Turnpike,Suite 198,Lebsackbury,31428-2261,-38.2386,57.2232,Hoeger LLC,Centralized empowering task-force,target end-to-end models

In [34]:
keep = ["id", "name", "username", "email", "phone", "address.city", "company.name"]
df_users = df_users[[c for c in keep if c in df_users.columns]]
df_users.columns = [c.replace("address.", "").replace("company.", "") for c in df_users.columns]
print(df_users.to_string(index=False))

 id                     name         username                     email                 phone           city               name
  1            Leanne Graham             Bret         Sincere@april.biz 1-770-736-8031 x56442    Gwenborough    Romaguera-Crona
  2             Ervin Howell        Antonette         Shanna@melissa.tv   010-692-6593 x09125    Wisokyburgh       Deckow-Crist
  3         Clementine Bauch         Samantha        Nathan@yesenia.net        1-463-123-4447  McKenziehaven Romaguera-Jacobson
  4         Patricia Lebsack         Karianne Julianne.OConner@kory.org     493-170-9623 x156    South Elvis      Robel-Corkery
  5         Chelsey Dietrich           Kamren  Lucio_Hettinger@annie.ca         (254)954-1289     Roscoeview        Keebler LLC
  6     Mrs. Dennis Schulist Leopoldo_Corkery   Karley_Dach@jasper.info  1-477-935-8478 x6430  South Christy  Considine-Lockman
  7          Kurtis Weissnat     Elwyn.Skiles    Telly.Hoeger@billy.biz          210.067.6132      Howemouth        Johns Group
  8 Nicholas Runolfsdottir V    Maxime_Nienow      Sherwood@rosamond.me     586.493.6943 x140      Aliyaview    Abernathy Group
  9          Glenna Reichert         Delphine   Chaim_McDermott@dana.io  (775)976-6794 x41206 Bartholomebury      Yost and Sons
 10       Clementina DuBuque   Moriah.Stanton    Rey.Padberg@karina.biz          024-648-3804    Lebsackbury         Hoeger LLC

In [38]:
print("\n--- Fetching /posts  (paginated, 10 per page) ---")

all_posts = []
page = 1
page_size = 10

--- Fetching /posts  (paginated, 10 per page) ---

In [39]:
while True:
    try:
        data = api_get("/posts", params={"_page": page, "_limit": page_size})
    except Exception:
        # Fallback: simulate 2 pages of 3 records each
        if page == 1:
            data = SAMPLE_POSTS[:3]
        elif page == 2:
            data = SAMPLE_POSTS[3:]
        else:
            data = []

    if not data:           # empty list = no more pages
        break

    all_posts.extend(data)
    print(f"  Page {page} → {len(data)} records  (total so far: {len(all_posts)})")

    if len(data) < page_size:   # last page (partial)
        break

    page += 1

  Page 1 → 10 records  (total so far: 10)
  Page 2 → 10 records  (total so far: 20)
  Page 3 → 10 records  (total so far: 30)
  Page 4 → 10 records  (total so far: 40)
  Page 5 → 10 records  (total so far: 50)
  Page 6 → 10 records  (total so far: 60)
  Page 7 → 10 records  (total so far: 70)
  Page 8 → 10 records  (total so far: 80)
  Page 9 → 10 records  (total so far: 90)
  Page 10 → 10 records  (total so far: 100)

In [41]:
all_posts

[{'userId': 1,
  'id': 1,
  'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit',
  'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'},
 {'userId': 1,
  'id': 2,
  'title': 'qui est esse',
  'body': 'est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla'},
 {'userId': 1,
  'id': 3,
  'title': 'ea molestias quasi exercitationem repellat qui ipsa sit aut',
  'body': 'et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut'},
 {'userId': 1,
  'id': 4,
  'title': 'eum et est occaecati',
  'body': 'ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit'},
 {'userId': 1,
  'id': 5,
  'title': 'nesciunt quas odio',
  'body': 'repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque'},
 {'userId': 1,
  'id': 6,
  'title': 'dolorem eum magni eos aperiam quia',
  'body': 'ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae'},
 {'userId': 1,
  'id': 7,
  'title': 'magnam facilis autem',
  'body': 'dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas'},
 {'userId': 1,
  'id': 8,
  'title': 'dolorem dolore est ipsam',
  'body': 'dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae'},
 {'userId': 1,
  'id': 9,
  'title': 'nesciunt iure omnis dolorem tempora et accusantium',
  'body': 'consectetur animi nesciunt iure dolore\nenim quia ad\nveniam autem ut quam aut nobis\net est aut quod aut provident voluptas autem voluptas'},
 {'userId': 1,
  'id': 10,
  'title': 'optio molestias id quia eum',
  'body': 'quo et expedita modi cum officia vel magni\ndoloribus qui repudiandae\nvero nisi sit\nquos veniam quod sed accusamus veritatis error'},
 {'userId': 2,
  'id': 11,
  'title': 'et ea vero quia laudantium autem',
  'body': 'delectus reiciendis molestiae occaecati non minima eveniet qui voluptatibus\naccusamus in eum beatae sit\nvel qui neque voluptates ut commodi qui incidunt\nut animi commodi'},
 {'userId': 2,
  'id': 12,
  'title': 'in quibusdam tempore odit est dolorem',
  'body': 'itaque id aut magnam\npraesentium quia et ea odit et ea voluptas et\nsapiente quia nihil amet occaecati quia id voluptatem\nincidunt ea est distinctio odio'},
 {'userId': 2,
  'id': 13,
  'title': 'dolorum ut in voluptas mollitia et saepe quo animi',
  'body': 'aut dicta possimus sint mollitia voluptas commodi quo doloremque\niste corrupti reiciendis voluptatem eius rerum\nsit cumque quod eligendi laborum minima\nperferendis recusandae assumenda consectetur porro architecto ipsum ipsam'},
 {'userId': 2,
  'id': 14,
  'title': 'voluptatem eligendi optio',
  'body': 'fuga et accusamus dolorum perferendis illo voluptas\nnon doloremque neque facere\nad qui dolorum molestiae beatae\nsed aut voluptas totam sit illum'},
 {'userId': 2,
  'id': 15,
  'title': 'eveniet quod temporibus',
  'body': 'reprehenderit quos placeat\nvelit minima officia dolores impedit repudiandae molestiae nam\nvoluptas recusandae quis delectus\nofficiis harum fugiat vitae'},
 {'userId': 2,
  'id': 16,
  'title': 'sint suscipit perspiciatis velit dolorum rerum ipsa laboriosam odio',
  'body': 'suscipit nam nisi quo aperiam aut\nasperiores eos fugit maiores voluptatibus quia\nvoluptatem quis ullam qui in alias quia est\nconsequatur magni mollitia accusamus ea nisi voluptate dicta'},
 {'userId': 2,
  'id': 17,
  'title': 'fugit voluptas sed molestias voluptatem provident',
  'body': 'eos voluptas et aut odit natus earum\naspernatur fuga molestiae ullam\ndeserunt ratione qui eos\nqui nihil ratione nemo velit ut aut id quo'},
 {'userId': 2,
  'id': 18,
  'title': 'voluptate et itaque vero tempora molestiae',
  'body': 'eveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluptatem vel debitis et magnam'},
 {'userId': 2,
  'id': 19,
  'title': 'adipisci placeat illum aut reiciendis qui',
  'body': 'illum quis cupiditate provident sit magnam\nea sed aut omnis\nveniam maiores ullam consequatur atque\nadipisci quo iste expedita sit quos voluptas'},
 {'userId': 2,
  'id': 20,
  'title': 'doloribus ad provident suscipit at',
  'body': 'qui consequuntur ducimus possimus quisquam amet similique\nsuscipit porro ipsam amet\neos veritatis officiis exercitationem vel fugit aut necessitatibus totam\nomnis rerum consequatur expedita quidem cumque explicabo'},
 {'userId': 3,
  'id': 21,
  'title': 'asperiores ea ipsam voluptatibus modi minima quia sint',
  'body': 'repellat aliquid praesentium dolorem quo\nsed totam minus non itaque\nnihil labore molestiae sunt dolor eveniet hic recusandae veniam\ntempora et tenetur expedita sunt'},
 {'userId': 3,
  'id': 22,
  'title': 'dolor sint quo a velit explicabo quia nam',
  'body': 'eos qui et ipsum ipsam suscipit aut\nsed omnis non odio\nexpedita earum mollitia molestiae aut atque rem suscipit\nnam impedit esse'},
 {'userId': 3,
  'id': 23,
  'title': 'maxime id vitae nihil numquam',
  'body': 'veritatis unde neque eligendi\nquae quod architecto quo neque vitae\nest illo sit tempora doloremque fugit quod\net et vel beatae sequi ullam sed tenetur perspiciatis'},
 {'userId': 3,
  'id': 24,
  'title': 'autem hic labore sunt dolores incidunt',
  'body': 'enim et ex nulla\nomnis voluptas quia qui\nvoluptatem consequatur numquam aliquam sunt\ntotam recusandae id dignissimos aut sed asperiores deserunt'},
 {'userId': 3,
  'id': 25,
  'title': 'rem alias distinctio quo quis',
  'body': 'ullam consequatur ut\nomnis quis sit vel consequuntur\nipsa eligendi ipsum molestiae et omnis error nostrum\nmolestiae illo tempore quia et distinctio'},
 {'userId': 3,
  'id': 26,
  'title': 'est et quae odit qui non',
  'body': 'similique esse doloribus nihil accusamus\nomnis dolorem fuga consequuntur reprehenderit fugit recusandae temporibus\nperspiciatis cum ut laudantium\nomnis aut molestiae vel vero'},
 {'userId': 3,
  'id': 27,
  'title': 'quasi id et eos tenetur aut quo autem',
  'body': 'eum sed dolores ipsam sint possimus debitis occaecati\ndebitis qui qui et\nut placeat enim earum aut odit facilis\nconsequatur suscipit necessitatibus rerum sed inventore temporibus consequatur'},
 {'userId': 3,
  'id': 28,
  'title': 'delectus ullam et corporis nulla voluptas sequi',
  'body': 'non et quaerat ex quae ad maiores\nmaiores recusandae totam aut blanditiis mollitia quas illo\nut voluptatibus voluptatem\nsimilique nostrum eum'},
 {'userId': 3,
  'id': 29,
  'title': 'iusto eius quod necessitatibus culpa ea',
  'body': 'odit magnam ut saepe sed non qui\ntempora atque nihil\naccusamus illum doloribus illo dolor\neligendi repudiandae odit magni similique sed cum maiores'},
 {'userId': 3,
  'id': 30,
  'title': 'a quo magni similique perferendis',
  'body': 'alias dolor cumque\nimpedit blanditiis non eveniet odio maxime\nblanditiis amet eius quis tempora quia autem rem\na provident perspiciatis quia'},
 {'userId': 4,
  'id': 31,
  'title': 'ullam ut quidem id aut vel consequuntur',
  'body': 'debitis eius sed quibusdam non quis consectetur vitae\nimpedit ut qui consequatur sed aut in\nquidem sit nostrum et maiores adipisci atque\nquaerat voluptatem adipisci repudiandae'},
 {'userId': 4,
  'id': 32,
  'title': 'doloremque illum aliquid sunt',
  'body': 'deserunt eos nobis asperiores et hic\nest debitis repellat molestiae optio\nnihil ratione ut eos beatae quibusdam distinctio maiores\nearum voluptates et aut adipisci ea maiores voluptas maxime'},
 {'userId': 4,
  'id': 33,
  'title': 'qui explicabo molestiae dolorem',
  'body': 'rerum ut et numquam laborum odit est sit\nid qui sint in\nquasi tenetur tempore aperiam et quaerat qui in\nrerum officiis sequi cumque quod'},
 {'userId': 4,
  'id': 34,
  'title': 'magnam ut rerum iure',
  'body': 'ea velit perferendis earum ut voluptatem voluptate itaque iusto\ntotam pariatur in\nnemo voluptatem voluptatem autem magni tempora minima in\nest distinctio qui assumenda accusamus dignissimos officia nesciunt nobis'},
 {'userId': 4,
  'id': 35,
  'title': 'id nihil consequatur molestias animi provident',
  'body': 'nisi error delectus possimus ut eligendi vitae\nplaceat eos harum cupiditate facilis reprehenderit voluptatem beatae\nmodi ducimus quo illum voluptas eligendi\net nobis quia fugit'},
 {'userId': 4,
  'id': 36,
  'title': 'fuga nam accusamus voluptas reiciendis itaque',
  'body': 'ad mollitia et omnis minus architecto odit\nvoluptas doloremque maxime aut non ipsa qui alias veniam\nblanditiis culpa aut quia nihil cumque facere et occaecati\nqui aspernatur quia eaque ut aperiam inventore'},
 {'userId': 4,
  'id': 37,
  'title': 'provident vel ut sit ratione est',
  'body': 'debitis et eaque non officia sed nesciunt pariatur vel\nvoluptatem iste vero et ea\nnumquam aut expedita ipsum nulla in\nvoluptates omnis consequatur aut enim officiis in quam qui'},
 {'userId': 4,
  'id': 38,
  'title': 'explicabo et eos deleniti nostrum ab id repellendus',
  'body': 'animi esse sit aut sit nesciunt assumenda eum voluptas\nquia voluptatibus provident quia necessitatibus ea\nrerum repudiandae quia voluptatem delectus fugit aut id quia\nratione optio eos iusto veniam iure'},
 {'userId': 4,
  'id': 39,
  'title': 'eos dolorem iste accusantium est eaque quam',
  'body': 'corporis rerum ducimus vel eum accusantium\nmaxime aspernatur a porro possimus iste omnis\nest in deleniti asperiores fuga aut\nvoluptas sapiente vel dolore minus voluptatem incidunt ex'},
 {'userId': 4,
  'id': 40,
  'title': 'enim quo cumque',
  'body': 'ut voluptatum aliquid illo tenetur nemo sequi quo facilis\nipsum rem optio mollitia quas\nvoluptatem eum voluptas qui\nunde omnis voluptatem iure quasi maxime voluptas nam'},
 {'userId': 5,
  'id': 41,
  'title': 'non est facere',
  'body': 'molestias id nostrum\nexcepturi molestiae dolore omnis repellendus quaerat saepe\nconsectetur iste quaerat tenetur asperiores accusamus ex ut\nnam quidem est ducimus sunt debitis saepe'},
 {'userId': 5,
  'id': 42,
  'title': 'commodi ullam sint et excepturi error explicabo praesentium voluptas',
  'body': 'odio fugit voluptatum ducimus earum autem est incidunt voluptatem\nodit reiciendis aliquam sunt sequi nulla dolorem\nnon facere repellendus voluptates quia\nratione harum vitae ut'},
 {'userId': 5,
  'id': 43,
  'title': 'eligendi iste nostrum consequuntur adipisci praesentium sit beatae perferendis',
  'body': 'similique fugit est\nillum et dolorum harum et voluptate eaque quidem\nexercitationem quos nam commodi possimus cum odio nihil nulla\ndolorum exercitationem magnam ex et a et distinctio debitis'},
 {'userId': 5,
  'id': 44,
  'title': 'optio dolor molestias sit',
  'body': 'temporibus est consectetur dolore\net libero debitis vel velit laboriosam quia\nipsum quibusdam qui itaque fuga rem aut\nea et iure quam sed maxime ut distinctio quae'},
 {'userId': 5,
  'id': 45,
  'title': 'ut numquam possimus omnis eius suscipit laudantium iure',
  'body': 'est natus reiciendis nihil possimus aut provident\nex et dolor\nrepellat pariatur est\nnobis rerum repellendus dolorem autem'},
 {'userId': 5,
  'id': 46,
  'title': 'aut quo modi neque nostrum ducimus',
  'body': 'voluptatem quisquam iste\nvoluptatibus natus officiis facilis dolorem\nquis quas ipsam\nvel et voluptatum in aliquid'},
 {'userId': 5,
  'id': 47,
  'title': 'quibusdam cumque rem aut deserunt',
  'body': 'voluptatem assumenda ut qui ut cupiditate aut impedit veniam\noccaecati nemo illum voluptatem laudantium\nmolestiae beatae rerum ea iure soluta nostrum\neligendi et voluptate'},
 {'userId': 5,
  'id': 48,
  'title': 'ut voluptatem illum ea doloribus itaque eos',
  'body': 'voluptates quo voluptatem facilis iure occaecati\nvel assumenda rerum officia et\nillum perspiciatis ab deleniti\nlaudantium repellat ad ut et autem reprehenderit'},
 {'userId': 5,
  'id': 49,
  'title': 'laborum non sunt aut ut assumenda perspiciatis voluptas',
  'body': 'inventore ab sint\nnatus fugit id nulla sequi architecto nihil quaerat\neos tenetur in in eum veritatis non\nquibusdam officiis aspernatur cumque aut commodi aut'},
 {'userId': 5,
  'id': 50,
  'title': 'repellendus qui recusandae incidunt voluptates tenetur qui omnis exercitationem',
  'body': 'error suscipit maxime adipisci consequuntur recusandae\nvoluptas eligendi et est et voluptates\nquia distinctio ab amet quaerat molestiae et vitae\nadipisci impedit sequi nesciunt quis consectetur'},
 {'userId': 6,
  'id': 51,
  'title': 'soluta aliquam aperiam consequatur illo quis voluptas',
  'body': 'sunt dolores aut doloribus\ndolore doloribus voluptates tempora et\ndoloremque et quo\ncum asperiores sit consectetur dolorem'},
 {'userId': 6,
  'id': 52,
  'title': 'qui enim et consequuntur quia animi quis voluptate quibusdam',
  'body': 'iusto est quibusdam fuga quas quaerat molestias\na enim ut sit accusamus enim\ntemporibus iusto accusantium provident architecto\nsoluta esse reprehenderit qui laborum'},
 {'userId': 6,
  'id': 53,
  'title': 'ut quo aut ducimus alias',
  'body': 'minima harum praesentium eum rerum illo dolore\nquasi exercitationem rerum nam\nporro quis neque quo\nconsequatur minus dolor quidem veritatis sunt non explicabo similique'},
 {'userId': 6,
  'id': 54,
  'title': 'sit asperiores ipsam eveniet odio non quia',
  'body': 'totam corporis dignissimos\nvitae dolorem ut occaecati accusamus\nex velit deserunt\net exercitationem vero incidunt corrupti mollitia'},
 {'userId': 6,
  'id': 55,
  'title': 'sit vel voluptatem et non libero',
  'body': 'debitis excepturi ea perferendis harum libero optio\neos accusamus cum fuga ut sapiente repudiandae\net ut incidunt omnis molestiae\nnihil ut eum odit'},
 {'userId': 6,
  'id': 56,
  'title': 'qui et at rerum necessitatibus',
  'body': 'aut est omnis dolores\nneque rerum quod ea rerum velit pariatur beatae excepturi\net provident voluptas corrupti\ncorporis harum reprehenderit dolores eligendi'},
 {'userId': 6,
  'id': 57,
  'title': 'sed ab est est',
  'body': 'at pariatur consequuntur earum quidem\nquo est laudantium soluta voluptatem\nqui ullam et est\net cum voluptas voluptatum repellat est'},
 {'userId': 6,
  'id': 58,
  'title': 'voluptatum itaque dolores nisi et quasi',
  'body': 'veniam voluptatum quae adipisci id\net id quia eos ad et dolorem\naliquam quo nisi sunt eos impedit error\nad similique veniam'},
 {'userId': 6,
  'id': 59,
  'title': 'qui commodi dolor at maiores et quis id accusantium',
  'body': 'perspiciatis et quam ea autem temporibus non voluptatibus qui\nbeatae a earum officia nesciunt dolores suscipit voluptas et\nanimi doloribus cum rerum quas et magni\net hic ut ut commodi expedita sunt'},
 {'userId': 6,
  'id': 60,
  'title': 'consequatur placeat omnis quisquam quia reprehenderit fugit veritatis facere',
  'body': 'asperiores sunt ab assumenda cumque modi velit\nqui esse omnis\nvoluptate et fuga perferendis voluptas\nillo ratione amet aut et omnis'},
 {'userId': 7,
  'id': 61,
  'title': 'voluptatem doloribus consectetur est ut ducimus',
  'body': 'ab nemo optio odio\ndelectus tenetur corporis similique nobis repellendus rerum omnis facilis\nvero blanditiis debitis in nesciunt doloribus dicta dolores\nmagnam minus velit'},
 {'userId': 7,
  'id': 62,
  'title': 'beatae enim quia vel',
  'body': 'enim aspernatur illo distinctio quae praesentium\nbeatae alias amet delectus qui voluptate distinctio\nodit sint accusantium autem omnis\nquo molestiae omnis ea eveniet optio'},
 {'userId': 7,
  'id': 63,
  'title': 'voluptas blanditiis repellendus animi ducimus error sapiente et suscipit',
  'body': 'enim adipisci aspernatur nemo\nnumquam omnis facere dolorem dolor ex quis temporibus incidunt\nab delectus culpa quo reprehenderit blanditiis asperiores\naccusantium ut quam in voluptatibus voluptas ipsam dicta'},
 {'userId': 7,
  'id': 64,
  'title': 'et fugit quas eum in in aperiam quod',
  'body': 'id velit blanditiis\neum ea voluptatem\nmolestiae sint occaecati est eos perspiciatis\nincidunt a error provident eaque aut aut qui'},
 {'userId': 7,
  'id': 65,
  'title': 'consequatur id enim sunt et et',
  'body': 'voluptatibus ex esse\nsint explicabo est aliquid cumque adipisci fuga repellat labore\nmolestiae corrupti ex saepe at asperiores et perferendis\nnatus id esse incidunt pariatur'},
 {'userId': 7,
  'id': 66,
  'title': 'repudiandae ea animi iusto',
  'body': 'officia veritatis tenetur vero qui itaque\nsint non ratione\nsed et ut asperiores iusto eos molestiae nostrum\nveritatis quibusdam et nemo iusto saepe'},
 {'userId': 7,
  'id': 67,
  'title': 'aliquid eos sed fuga est maxime repellendus',
  'body': 'reprehenderit id nostrum\nvoluptas doloremque pariatur sint et accusantium quia quod aspernatur\net fugiat amet\nnon sapiente et consequatur necessitatibus molestiae'},
 {'userId': 7,
  'id': 68,
  'title': 'odio quis facere architecto reiciendis optio',
  'body': 'magnam molestiae perferendis quisquam\nqui cum reiciendis\nquaerat animi amet hic inventore\nea quia deleniti quidem saepe porro velit'},
 {'userId': 7,
  'id': 69,
  'title': 'fugiat quod pariatur odit minima',
  'body': 'officiis error culpa consequatur modi asperiores et\ndolorum assumenda voluptas et vel qui aut vel rerum\nvoluptatum quisquam perspiciatis quia rerum consequatur totam quas\nsequi commodi repudiandae asperiores et saepe a'},
 {'userId': 7,
  'id': 70,
  'title': 'voluptatem laborum magni',
  'body': 'sunt repellendus quae\nest asperiores aut deleniti esse accusamus repellendus quia aut\nquia dolorem unde\neum tempora esse dolore'},
 {'userId': 8,
  'id': 71,
  'title': 'et iusto veniam et illum aut fuga',
  'body': 'occaecati a doloribus\niste saepe consectetur placeat eum voluptate dolorem et\nqui quo quia voluptas\nrerum ut id enim velit est perferendis'},
 {'userId': 8,
  'id': 72,
  'title': 'sint hic doloribus consequatur eos non id',
  'body': 'quam occaecati qui deleniti consectetur\nconsequatur aut facere quas exercitationem aliquam hic voluptas\nneque id sunt ut aut accusamus\nsunt consectetur expedita inventore velit'},
 {'userId': 8,
  'id': 73,
  'title': 'consequuntur deleniti eos quia temporibus ab aliquid at',
  'body': 'voluptatem cumque tenetur consequatur expedita ipsum nemo quia explicabo\naut eum minima consequatur\ntempore cumque quae est et\net in consequuntur voluptatem voluptates aut'},
 {'userId': 8,
  'id': 74,
  'title': 'enim unde ratione doloribus quas enim ut sit sapiente',
  'body': 'odit qui et et necessitatibus sint veniam\nmollitia amet doloremque molestiae commodi similique magnam et quam\nblanditiis est itaque\nquo et tenetur ratione occaecati molestiae tempora'},
 {'userId': 8,
  'id': 75,
  'title': 'dignissimos eum dolor ut enim et delectus in',
  'body': 'commodi non non omnis et voluptas sit\nautem aut nobis magnam et sapiente voluptatem\net laborum repellat qui delectus facilis temporibus\nrerum amet et nemo voluptate expedita adipisci error dolorem'},
 {'userId': 8,
  'id': 76,
  'title': 'doloremque officiis ad et non perferendis',
  'body': 'ut animi facere\ntotam iusto tempore\nmolestiae eum aut et dolorem aperiam\nquaerat recusandae totam odio'},
 {'userId': 8,
  'id': 77,
  'title': 'necessitatibus quasi exercitationem odio',

In [42]:
df_posts = pd.DataFrame(all_posts)

In [43]:
df_posts

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...
...,...,...,...,...
95,10,96,quaerat velit veniam amet cupiditate aut numqu...,in non odio excepturi sint eum\nlabore volupta...
96,10,97,quas fugiat ut perspiciatis vero provident,eum non blanditiis soluta porro quibusdam volu...
97,10,98,laboriosam dolor voluptates,doloremque ex facilis sit sint culpa\nsoluta a...
98,10,99,temporibus sit alias delectus eligendi possimu...,quo deleniti praesentium dicta non quod\naut e...
99,10,100,at nam consequatur ea labore ea harum,cupiditate quo est a modi nesciunt soluta\nips...

In [44]:
print(f"\nTotal posts fetched: {len(df_posts)}")
print(df_posts.head(3).to_string(index=False))

Total posts fetched: 100
 userId  id                                                                      title                                                                                                                                                                                                              body
      1   1 sunt aut facere repellat provident occaecati excepturi optio reprehenderit                                                 quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto
      1   2                                                               qui est esse est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla
      1   3                ea molestias quasi exercitationem repellat qui ipsa sit aut                                           et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut

In [45]:
# --------------------------------------------------------------------------
# 2C. Fetch related resource  (/comments for a specific post)
# --------------------------------------------------------------------------

In [46]:
print("\n--- Fetching comments for post_id=1 ---")
try:
    comments_raw = api_get("/comments", params={"postId": 1})
    print("  (live API)")
except Exception:
    comments_raw = SAMPLE_COMMENTS
    print("  (network unavailable — using sample data)")

df_comments = pd.DataFrame(comments_raw)
print(df_comments[["id", "name", "email", "body"]].to_string(index=False))

--- Fetching comments for post_id=1 ---
  (live API)
 id                                      name                  email                                                                                                                                                                                                                          body
  1              id labore ex et quam laborum     Eliseo@gardner.biz                                                                       laudantium enim quasi est quidem magnam voluptate ipsam eos\ntempora quo necessitatibus\ndolor quam autem quasi\nreiciendis et nam sapiente accusantium
  2 quo vero reiciendis velit similique earum Jayne_Kuhic@sydney.com                                                   est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et
  3             odio adipisci rerum aut animi    Nikita@garfield.biz quia molestiae reprehenderit quasi aspernatur\naut expedita occaecati aliquam eveniet laudantium\nomnis quibusdam delectus saepe quia accusamus maiores nam est\ncum et ducimus et vero voluptates excepturi deleniti ratione
  4                            alias odio sit          Lew@alysha.tv                                                                 non et atque\noccaecati deserunt quas accusantium unde odit nobis qui voluptatem\nquia voluptas consequuntur itaque dolor\net qui rerum deleniti ut occaecati
  5     vero eaque aliquid doloribus et culpa      Hayden@althea.biz                                                                                       harum non quasi et ratione\ntempore iure ex voluptates in ratione\nharum architecto fugit inventore cupiditate\nvoluptates magni quo et

In [47]:
print("\n" + "="*60)
print("  SECTION 3 — DATABASE INGESTION")
print("  (SQLite demo — swap one line for Postgres or Snowflake)")
print("="*60)

============================================================
  SECTION 3 — DATABASE INGESTION
  (SQLite demo — swap one line for Postgres or Snowflake)
============================================================

In [48]:
DB_FILE = Path("data/source.db")

In [73]:
conn = sqlite3.connect(DB_FILE)
cur  = conn.cursor()

In [50]:
cur.executescript("""
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS employees;

CREATE TABLE transactions (
    txn_id      INTEGER PRIMARY KEY,
    customer_id INTEGER,
    product     TEXT,
    amount      REAL,
    status      TEXT,
    created_at  TEXT,
    updated_at  TEXT
);

CREATE TABLE employees (
    emp_id     INTEGER PRIMARY KEY,
    name       TEXT,
    department TEXT,
    salary     REAL,
    hire_date  TEXT
);
""")

In [51]:
cur.executemany("INSERT INTO transactions VALUES (?,?,?,?,?,?,?)", [
    (1, 1, "Laptop",     999.99, "completed", "2024-01-10", "2024-01-10 09:00"),
    (2, 2, "Keyboard",    79.99, "completed", "2024-01-15", "2024-01-15 14:00"),
    (3, 3, "Monitor",    349.99, "shipped",   "2024-02-01", "2024-02-02 08:00"),
    (4, 1, "Mouse",       25.00, "completed", "2024-02-10", "2024-02-10 16:00"),
    (5, 4, "Tablet",     599.99, "completed", "2024-02-20", "2024-02-20 11:00"),
    (6, 5, "Headphones", 199.99, "completed", "2024-03-01", "2024-03-01 09:00"),
    (7, 2, "USB Hub",     49.99, "pending",   "2024-03-05", "2024-03-05 13:00"),
    (8, 6, "Workstation",1299.99,"completed", "2024-03-10", "2024-03-10 10:00"),
])

In [52]:
cur.executemany("INSERT INTO employees VALUES (?,?,?,?,?)", [
    (101, "Sarah Connor", "Engineering", 95000, "2021-06-01"),
    (102, "John Doe",     "Sales",       72000, "2022-01-15"),
    (103, "Jane Smith",   "HR",          65000, "2020-09-10"),
    (104, "Mike Ross",    "Engineering", 88000, "2023-03-20"),
    (105, "Rachel Zane",  "Legal",       98000, "2019-11-05"),
])

In [53]:
conn.commit()

In [54]:
print("Database seeded: transactions(8 rows) + employees(5 rows)")

Database seeded: transactions(8 rows) + employees(5 rows)

In [55]:
print("\n--- Read full table: transactions ---")
df_txn = pd.read_sql("SELECT * FROM transactions", conn)
print(df_txn.to_string(index=False))

--- Read full table: transactions ---
 txn_id  customer_id     product  amount    status created_at       updated_at
      1            1      Laptop  999.99 completed 2024-01-10 2024-01-10 09:00
      2            2    Keyboard   79.99 completed 2024-01-15 2024-01-15 14:00
      3            3     Monitor  349.99   shipped 2024-02-01 2024-02-02 08:00
      4            1       Mouse   25.00 completed 2024-02-10 2024-02-10 16:00
      5            4      Tablet  599.99 completed 2024-02-20 2024-02-20 11:00
      6            5  Headphones  199.99 completed 2024-03-01 2024-03-01 09:00
      7            2     USB Hub   49.99   pending 2024-03-05 2024-03-05 13:00
      8            6 Workstation 1299.99 completed 2024-03-10 2024-03-10 10:00

In [56]:

print("\n--- Read full table: employees ---")
df_emp = pd.read_sql("SELECT * FROM employees", conn)
print(df_emp.to_string(index=False))

--- Read full table: employees ---
 emp_id         name  department  salary  hire_date
    101 Sarah Connor Engineering 95000.0 2021-06-01
    102     John Doe       Sales 72000.0 2022-01-15
    103   Jane Smith          HR 65000.0 2020-09-10
    104    Mike Ross Engineering 88000.0 2023-03-20
    105  Rachel Zane       Legal 98000.0 2019-11-05

In [57]:
print("\n--- Filter: transactions where amount > 200 ---")
df_big = pd.read_sql(
    "SELECT * FROM transactions WHERE amount > 200 ORDER BY amount DESC",
    conn
)
print(df_big.to_string(index=False))

--- Filter: transactions where amount > 200 ---
 txn_id  customer_id     product  amount    status created_at       updated_at
      8            6 Workstation 1299.99 completed 2024-03-10 2024-03-10 10:00
      1            1      Laptop  999.99 completed 2024-01-10 2024-01-10 09:00
      5            4      Tablet  599.99 completed 2024-02-20 2024-02-20 11:00
      3            3     Monitor  349.99   shipped 2024-02-01 2024-02-02 08:00

In [58]:
print("\n--- Chunked read (chunk_size=3) ---")
offset = 0
chunk_size = 3
chunk_num  = 0

--- Chunked read (chunk_size=3) ---

In [59]:
while True:
    chunk = pd.read_sql(
        f"SELECT * FROM transactions LIMIT {chunk_size} OFFSET {offset}",
        conn
    )
    if chunk.empty:
        break
    chunk_num += 1
    print(f"  Chunk {chunk_num}: {len(chunk)} rows")
    offset += chunk_size

print(f"  Total chunks: {chunk_num}")

  Chunk 1: 3 rows
  Chunk 2: 3 rows
  Chunk 3: 2 rows
  Total chunks: 3

In [62]:
# import psycopg2
# conn = psycopg2.connect(
#   host="localhost", port=5432,
#   dbname="test", user="postgres", password="1234"
# )

In [64]:
# import snowflake.connector
# conn = snowflake.connector.connect(
#     user='detrainings01'
#     , password='DataEngineering@2026'
#     , account='sqqpjbk-pi02317'
#     , warehouse='COMPUTE_WH'
#     , role='SYSADMIN'
#     , database='MY_DB1'
#     , schema='RAW'
# )

20:41:34  [INFO    ]  Snowflake Connector for Python Version: 4.2.0, Python Version: 3.11.9, Platform: Windows-10-10.0.26200-SP0
20:41:34  [INFO    ]  Connecting to GLOBAL Snowflake domain
20:41:34  [INFO    ]  Found credentials in shared credentials file: ~/.aws/credentials

In [65]:
print("\n" + "="*60)
print("  SECTION 4 — INCREMENTAL vs FULL LOAD")
print("="*60)

============================================================
  SECTION 4 — INCREMENTAL vs FULL LOAD
============================================================

In [66]:
WATERMARK_FILE = Path("data/watermark.json")

In [67]:
def load_watermark(table_name):
    """Read the saved watermark for a table. Returns None if first run."""
    if not WATERMARK_FILE.exists():
        return None
    data = json.loads(WATERMARK_FILE.read_text())
    return data.get(table_name)

In [68]:
def save_watermark(table_name, value):
    """Save the watermark after a successful load."""
    data = {}
    if WATERMARK_FILE.exists():
        data = json.loads(WATERMARK_FILE.read_text())
    data[table_name] = str(value)
    WATERMARK_FILE.write_text(json.dumps(data, indent=2))
    print(f"  Watermark saved: {table_name} = {value}")

In [70]:
def full_load(connection, table_name):
    """Read every row from the table."""
    print(f"\n[FULL LOAD] Reading all rows from '{table_name}' ...")
    df = pd.read_sql(f"SELECT * FROM {table_name}", connection)
    print(f"  Loaded: {len(df)} rows")
    print(df.to_string(index=False))
    # Save the latest timestamp as the new watermark
    if "updated_at" in df.columns:
        save_watermark(table_name, df["updated_at"].max())
    return df

In [71]:
def incremental_load(connection, table_name, timestamp_col="updated_at"):
    """Read only rows newer than the last watermark."""
    last_ts = load_watermark(table_name)

    if last_ts is None:
        print(f"\n[INCREMENTAL] No watermark found → running full load instead.")
        return full_load(connection, table_name)

    print(f"\n[INCREMENTAL] Loading '{table_name}' where {timestamp_col} > '{last_ts}' ...")
    df = pd.read_sql(
        f"SELECT * FROM {table_name} WHERE {timestamp_col} > '{last_ts}'",
        connection
    )

    if df.empty:
        print("  No new rows — already up to date.")
        return df

    print(f"  Loaded: {len(df)} new rows")
    print(df.to_string(index=False))
    save_watermark(table_name, df[timestamp_col].max())
    return df

In [72]:
if WATERMARK_FILE.exists():
    WATERMARK_FILE.unlink()

print("""
How it works:
  Run 1 → no watermark → full load   → saves watermark = last updated_at
  Run 2 → same data    → 0 new rows  (nothing changed)
  Run 3 → new rows     → only new rows loaded, watermark advances
  Run 4 → force full   → all rows loaded again
""")

How it works:
  Run 1 → no watermark → full load   → saves watermark = last updated_at
  Run 2 → same data    → 0 new rows  (nothing changed)
  Run 3 → new rows     → only new rows loaded, watermark advances
  Run 4 → force full   → all rows loaded again

In [74]:
incremental_load(conn, "transactions")

[INCREMENTAL] No watermark found → running full load instead.

[FULL LOAD] Reading all rows from 'transactions' ...
  Loaded: 8 rows
 txn_id  customer_id     product  amount    status created_at       updated_at
      1            1      Laptop  999.99 completed 2024-01-10 2024-01-10 09:00
      2            2    Keyboard   79.99 completed 2024-01-15 2024-01-15 14:00
      3            3     Monitor  349.99   shipped 2024-02-01 2024-02-02 08:00
      4            1       Mouse   25.00 completed 2024-02-10 2024-02-10 16:00
      5            4      Tablet  599.99 completed 2024-02-20 2024-02-20 11:00
      6            5  Headphones  199.99 completed 2024-03-01 2024-03-01 09:00
      7            2     USB Hub   49.99   pending 2024-03-05 2024-03-05 13:00
      8            6 Workstation 1299.99 completed 2024-03-10 2024-03-10 10:00
  Watermark saved: transactions = 2024-03-10 10:00

,txn_id,customer_id,product,amount,status,created_at,updated_at
0,1,1,Laptop,999.99,completed,2024-01-10,2024-01-10 09:00
1,2,2,Keyboard,79.99,completed,2024-01-15,2024-01-15 14:00
2,3,3,Monitor,349.99,shipped,2024-02-01,2024-02-02 08:00
3,4,1,Mouse,25.00,completed,2024-02-10,2024-02-10 16:00
4,5,4,Tablet,599.99,completed,2024-02-20,2024-02-20 11:00
5,6,5,Headphones,199.99,completed,2024-03-01,2024-03-01 09:00
6,7,2,USB Hub,49.99,pending,2024-03-05,2024-03-05 13:00
7,8,6,Workstation,1299.99,completed,2024-03-10,2024-03-10 10:00

In [75]:
# Run 2 — nothing new
print("─" * 40)
print("RUN 2 — Re-run immediately (no new data)")
incremental_load(conn, "transactions")

────────────────────────────────────────
RUN 2 — Re-run immediately (no new data)

[INCREMENTAL] Loading 'transactions' where updated_at > '2024-03-10 10:00' ...
  No new rows — already up to date.

Empty DataFrame
Columns: [txn_id, customer_id, product, amount, status, created_at, updated_at]
Index: []

In [77]:
print("─" * 40)
print("RUN 3 — Adding 3 new rows then running incremental")
conn.executemany("INSERT INTO transactions VALUES (?,?,?,?,?,?,?)", [
    (9,  7, "Printer",   459.99, "completed", "2024-04-01", "2024-04-01 08:00"),
    (10, 8, "Speaker",   129.99, "pending",   "2024-04-02", "2024-04-02 10:00"),
    (11, 3, "MacBook",  2499.99, "completed", "2024-04-05", "2024-04-05 14:00"),
])

────────────────────────────────────────
RUN 3 — Adding 3 new rows then running incremental

IntegrityError: UNIQUE constraint failed: transactions.txn_id

In [78]:
conn.commit()

In [79]:
print("  3 rows inserted.")
incremental_load(conn, "transactions")

  3 rows inserted.

[INCREMENTAL] Loading 'transactions' where updated_at > '2024-03-10 10:00' ...
  Loaded: 3 new rows
 txn_id  customer_id product  amount    status created_at       updated_at
      9            7 Printer  459.99 completed 2024-04-01 2024-04-01 08:00
     10            8 Speaker  129.99   pending 2024-04-02 2024-04-02 10:00
     11            3 MacBook 2499.99 completed 2024-04-05 2024-04-05 14:00
  Watermark saved: transactions = 2024-04-05 14:00

,txn_id,customer_id,product,amount,status,created_at,updated_at
0,9,7,Printer,459.99,completed,2024-04-01,2024-04-01 08:00
1,10,8,Speaker,129.99,pending,2024-04-02,2024-04-02 10:00
2,11,3,MacBook,2499.99,completed,2024-04-05,2024-04-05 14:00

In [80]:
print("─" * 40)
print("RUN 4 — Force full load (reloads everything)")
full_load(conn, "transactions")

────────────────────────────────────────
RUN 4 — Force full load (reloads everything)

[FULL LOAD] Reading all rows from 'transactions' ...
  Loaded: 11 rows
 txn_id  customer_id     product  amount    status created_at       updated_at
      1            1      Laptop  999.99 completed 2024-01-10 2024-01-10 09:00
      2            2    Keyboard   79.99 completed 2024-01-15 2024-01-15 14:00
      3            3     Monitor  349.99   shipped 2024-02-01 2024-02-02 08:00
      4            1       Mouse   25.00 completed 2024-02-10 2024-02-10 16:00
      5            4      Tablet  599.99 completed 2024-02-20 2024-02-20 11:00
      6            5  Headphones  199.99 completed 2024-03-01 2024-03-01 09:00
      7            2     USB Hub   49.99   pending 2024-03-05 2024-03-05 13:00
      8            6 Workstation 1299.99 completed 2024-03-10 2024-03-10 10:00
      9            7     Printer  459.99 completed 2024-04-01 2024-04-01 08:00
     10            8     Speaker  129.99   pending 2024-04-02 2024-04-02 10:00
     11            3     MacBook 2499.99 completed 2024-04-05 2024-04-05 14:00
  Watermark saved: transactions = 2024-04-05 14:00

,txn_id,customer_id,product,amount,status,created_at,updated_at
0,1,1,Laptop,999.99,completed,2024-01-10,2024-01-10 09:00
1,2,2,Keyboard,79.99,completed,2024-01-15,2024-01-15 14:00
2,3,3,Monitor,349.99,shipped,2024-02-01,2024-02-02 08:00
3,4,1,Mouse,25.00,completed,2024-02-10,2024-02-10 16:00
4,5,4,Tablet,599.99,completed,2024-02-20,2024-02-20 11:00
5,6,5,Headphones,199.99,completed,2024-03-01,2024-03-01 09:00
6,7,2,USB Hub,49.99,pending,2024-03-05,2024-03-05 13:00
7,8,6,Workstation,1299.99,completed,2024-03-10,2024-03-10 10:00
8,9,7,Printer,459.99,completed,2024-04-01,2024-04-01 08:00
9,10,8,Speaker,129.99,pending,2024-04-02,2024-04-02 10:00
10,11,3,MacBook,2499.99,completed,2024-04-05,2024-04-05 14:00

In [81]:
print("\n" + "="*60)
print("  SECTION 5 — CAPSTONE: MULTI-SOURCE PIPELINE")
print("="*60)

============================================================
  SECTION 5 — CAPSTONE: MULTI-SOURCE PIPELINE
============================================================

In [82]:
print("\nStep 1: Read files")
df_c = pd.read_csv(RAW / "customers.csv")

Step 1: Read files

In [83]:
df_c

   customer_id           name            email         city    tier
0            1  Alice Johnson  alice@email.com     New York    Gold
1            2      Bob Smith    bob@email.com      Chicago  Silver
2            3    Carol White  carol@email.com  Los Angeles    Gold
3            4      David Lee  david@email.com      Houston  Bronze
4            5      Eva Brown    eva@email.com      Phoenix  Silver

In [84]:
with open(RAW / "orders.json") as f:
    df_o = pd.DataFrame(json.load(f))

In [85]:
df_c["source"] = "file:customers"
df_o["source"] = "file:orders"

In [87]:
file_df = pd.concat([df_c, df_o], ignore_index=True)
print(f"  Files → {len(file_df)} rows")

  Files → 10 rows

In [88]:
file_df

,customer_id,name,email,city,tier,source,order_id,product,qty,price,status
0,1,Alice Johnson,alice@email.com,New York,Gold,file:customers,NaN,NaN,NaN,NaN,NaN
1,2,Bob Smith,bob@email.com,Chicago,Silver,file:customers,NaN,NaN,NaN,NaN,NaN
2,3,Carol White,carol@email.com,Los Angeles,Gold,file:customers,NaN,NaN,NaN,NaN,NaN
3,4,David Lee,david@email.com,Houston,Bronze,file:customers,NaN,NaN,NaN,NaN,NaN
4,5,Eva Brown,eva@email.com,Phoenix,Silver,file:customers,NaN,NaN,NaN,NaN,NaN
5,1,NaN,NaN,NaN,NaN,file:orders,101.0,Laptop,1.0,999.99,delivered
6,2,NaN,NaN,NaN,NaN,file:orders,102.0,Mouse,2.0,25.00,shipped
7,3,NaN,NaN,NaN,NaN,file:orders,103.0,Monitor,1.0,349.99,pending
8,1,NaN,NaN,NaN,NaN,file:orders,104.0,Keyboard,1.0,79.99,delivered
9,5,NaN,NaN,NaN,NaN,file:orders,105.0,Webcam,1.0,89.99,shipped

In [89]:
print("\nStep 2: Fetch from API")

Step 2: Fetch from API

In [90]:
try:
    raw_users = api_get("/users")
    api_df = pd.json_normalize(raw_users)[["id", "name", "email"]]
    api_df.columns = ["customer_id", "name", "email"]
    api_df["source"] = "api:users"
    print(f"  API → {len(api_df)} rows")
except Exception as e:
    print(f"  API failed ({e}), skipping.")
    api_df = pd.DataFrame()

  API → 10 rows

In [91]:
raw_users = api_get("/users")

In [93]:
pd.json_normalize(raw_users)[["id", "name", "email"]]

   id                      name                      email
0   1             Leanne Graham          Sincere@april.biz
1   2              Ervin Howell          Shanna@melissa.tv
2   3          Clementine Bauch         Nathan@yesenia.net
3   4          Patricia Lebsack  Julianne.OConner@kory.org
4   5          Chelsey Dietrich   Lucio_Hettinger@annie.ca
5   6      Mrs. Dennis Schulist    Karley_Dach@jasper.info
6   7           Kurtis Weissnat     Telly.Hoeger@billy.biz
7   8  Nicholas Runolfsdottir V       Sherwood@rosamond.me
8   9           Glenna Reichert    Chaim_McDermott@dana.io
9  10        Clementina DuBuque     Rey.Padberg@karina.biz

In [94]:
# Step 3 — Database (incremental)
print("\nStep 3: Database (incremental)")
db_df = pd.read_sql("SELECT * FROM transactions", conn)
db_df["source"] = "db:transactions"
print(f"  Database → {len(db_df)} rows")

Step 3: Database (incremental)
  Database → 11 rows

In [95]:
# Step 4 — Merge
print("\nStep 4: Merge all sources")
all_dfs = [df for df in [file_df, api_df, db_df] if not df.empty]
merged = pd.concat(all_dfs, ignore_index=True)
merged.drop_duplicates(inplace=True)
merged["ingested_at"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"  Merged → {len(merged)} rows, {len(merged.columns)} columns")

Step 4: Merge all sources
  Merged → 31 rows, 16 columns

In [96]:
merged

,customer_id,name,email,city,tier,source,order_id,product,qty,price,status,txn_id,amount,created_at,updated_at,ingested_at
0,1,Alice Johnson,alice@email.com,New York,Gold,file:customers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-28 20:50:58
1,2,Bob Smith,bob@email.com,Chicago,Silver,file:customers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-28 20:50:58
2,3,Carol White,carol@email.com,Los Angeles,Gold,file:customers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-28 20:50:58
3,4,David Lee,david@email.com,Houston,Bronze,file:customers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-28 20:50:58
4,5,Eva Brown,eva@email.com,Phoenix,Silver,file:customers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-28 20:50:58
5,1,NaN,NaN,NaN,NaN,file:orders,101.0,Laptop,1.0,999.99,delivered,NaN,NaN,NaN,NaN,2026-02-28 20:50:58
6,2,NaN,NaN,NaN,NaN,file:orders,102.0,Mouse,2.0,25.00,shipped,NaN,NaN,NaN,NaN,2026-02-28 20:50:58
7,3,NaN,NaN,NaN,NaN,file:orders,103.0,Monitor,1.0,349.99,pending,NaN,NaN,NaN,NaN,2026-02-28 20:50:58
8,1,NaN,NaN,NaN,NaN,file:orders,104.0,Keyboard,1.0,79.99,delivered,NaN,NaN,NaN,NaN,2026-02-28 20:50:58
9,5,NaN,NaN,NaN,NaN,file:orders,105.0,Webcam,1.0,89.99,shipped,NaN,NaN,NaN,NaN,2026-02-28 20:50:58
10,1,Leanne Graham,Sincere@april.biz,NaN,NaN,api:users,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-28 20:50:58
11,2,Ervin Howell,Shanna@melissa.tv,NaN,NaN,api:users,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-28 20:50:58
12,3,Clementine Bauch,Nathan@yesenia.net,NaN,NaN,api:users,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-28 20:50:58
13,4,Patricia Lebsack,Julianne.OConner@kory.org,NaN,NaN,api:users,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-28 20:50:58
14,5,Chelsey Dietrich,Lucio_Hettinger@annie.ca,NaN,NaN,api:users,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-28 20:50:58
15,6,Mrs. Dennis Schulist,Karley_Dach@jasper.info,NaN,NaN,api:users,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-28 20:50:58
16,7,Kurtis Weissnat,Telly.Hoeger@billy.biz,NaN,NaN,api:users,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-28 20:50:58
17,8,Nicholas Runolfsdottir V,Sherwood@rosamond.me,NaN,NaN,api:users,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-28 20:50:58
18,9,Glenna Reichert,Chaim_McDermott@dana.io,NaN,NaN,api:users,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-28 20:50:58
19,10,Clementina DuBuque,Rey.Padberg@karina.biz,NaN,NaN,api:users,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-28 20:50:58
20,1,NaN,NaN,NaN,NaN,db:transactions,NaN,Laptop,NaN,NaN,completed,1.0,999.99,2024-01-10,2024-01-10 09:00,2026-02-28 20:50:58
21,2,NaN,NaN,NaN,NaN,db:transactions,NaN,Keyboard,NaN,NaN,completed,2.0,79.99,2024-01-15,2024-01-15 14:00,2026-02-28 20:50:58
22,3,NaN,NaN,NaN,NaN,db:transactions,NaN,Monitor,NaN,NaN,shipped,3.0,349.99,2024-02-01,2024-02-02 08:00,2026-02-28 20:50:58
23,1,NaN,NaN,NaN,NaN,db:transactions,NaN,Mouse,NaN,NaN,completed,4.0,25.00,2024-02-10,2024-02-10 16:00,2026-02-28 20:50:58
24,4,NaN,NaN,NaN,NaN,db:transactions,NaN,Tablet,NaN,NaN,completed,5.0,599.99,2024-02-20,2024-02-20 11:00,2026-02-28 20:50:58
25,5,NaN,NaN,NaN,NaN,db:transactions,NaN,Headphones,NaN,NaN,completed,6.0,199.99,2024-03-01,2024-03-01 09:00,2026-02-28 20:50:58
26,2,NaN,NaN,NaN,NaN,db:transactions,NaN,USB Hub,NaN,NaN,pending,7.0,49.99,2024-03-05,2024-03-05 13:00,2026-02-28 20:50:58
27,6,NaN,NaN,NaN,NaN,db:transactions,NaN,Workstation,NaN,NaN,completed,8.0,1299.99,2024-03-10,2024-03-10 10:00,2026-02-28 20:50:58
28,7,NaN,NaN,NaN,NaN,db:transactions,NaN,Printer,NaN,NaN,completed,9.0,459.99,2024-04-01,2024-04-01 08:00,2026-02-28 20:50:58
29,8,NaN,NaN,NaN,NaN,db:transactions,NaN,Speaker,NaN,NaN,pending,10.0,129.99,2024-04-02,2024-04-02 10:00,2026-02-28 20:50:58
30,3,NaN,NaN,NaN,NaN,db:transactions,NaN,MacBook,NaN,NaN,completed,11.0,2499.99,2024-04-05,2024-04-05 14:00,2026-02-28 20:50:58

In [97]:
print("\nStep 5: Save output")
ts = datetime.now().strftime("%Y%m%d_%H%M%S")
out = PROCESSED / f"pipeline_output_{ts}.csv"
merged.to_csv(out, index=False)
print(f"  Saved → {out}")

Step 5: Save output
  Saved → data\processed\pipeline_output_20260228_205139.csv

In [98]:
print("\n" + "="*60)
print("  PIPELINE COMPLETE")
print("="*60)
print(f"  File rows     : {len(file_df)}")
print(f"  API rows      : {len(api_df)}")
print(f"  DB rows       : {len(db_df)}")
print(f"  Total merged  : {len(merged)}")
print(f"  Output        : {out.name}")

============================================================
  PIPELINE COMPLETE
============================================================
  File rows     : 10
  API rows      : 10
  DB rows       : 11
  Total merged  : 31
  Output        : pipeline_output_20260228_205139.csv

In [99]:
source_counts = merged["source"].value_counts().to_dict()
for src, cnt in source_counts.items():
    print(f"    {src}: {cnt} rows")

    db:transactions: 11 rows
    api:users: 10 rows
    file:orders: 5 rows
    file:customers: 5 rows

In [100]:
conn.close()